import { env } from "cloudflare:workers";
import { NextRequest,NextResponse } from "next/server";
import { getMember } from "@/src/auth/member";

export const dynamic="force-dynamic";
function db(){if(!env.DB)throw new Error("Database unavailable");return env.DB}
async function ensure(){await db().prepare(`CREATE TABLE IF NOT EXISTS member_profiles (member_id TEXT PRIMARY KEY,full_name TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',email TEXT NOT NULL DEFAULT '',business_type TEXT NOT NULL DEFAULT '',address TEXT NOT NULL DEFAULT '',province TEXT NOT NULL DEFAULT '',postcode TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
async function profile(){const member=await getMember();if(!member)return null;await ensure();const details=await db().prepare("SELECT full_name,phone,email,business_type,address,province,postcode,updated_at FROM member_profiles WHERE member_id=?").bind(member.id).first<Record<string,string>>();return {...member,full_name:"",phone:"",email:"",business_type:"",address:"",province:"",postcode:"",...(details??{})}}

export async function GET(){try{const data=await profile();if(!data)return NextResponse.json({error:"Sign in required"},{status:401});return NextResponse.json({profile:data})}catch(error){console.error("member-profile:get",error);return NextResponse.json({error:"Profile is temporarily unavailable"},{status:503})}}

export async function PATCH(request:NextRequest){try{const member=await getMember();if(!member)return NextResponse.json({error:"Sign in required"},{status:401});await ensure();const body=await request.json();const clean=(key:string,max:number)=>String(body[key]??"").trim().slice(0,max);const fullName=clean("full_name",120),phone=clean("phone",30),email=clean("email",160),businessType=clean("business_type",80),address=clean("address",800),province=clean("province",100),postcode=clean("postcode",10);if(phone&& !/^0\d{8,9}$/.test(phone.replace(/[-\s]/g,"")))return NextResponse.json({error:"Invalid phone number"},{status:400});if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return NextResponse.json({error:"Invalid email"},{status:400});await db().prepare(`INSERT INTO member_profiles (member_id,full_name,phone,email,business_type,address,province,postcode,updated_at) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(member_id) DO UPDATE SET full_name=excluded.full_name,phone=excluded.phone,email=excluded.email,business_type=excluded.business_type,address=excluded.address,province=excluded.province,postcode=excluded.postcode,updated_at=CURRENT_TIMESTAMP`).bind(member.id,fullName,phone,email,businessType,address,province,postcode).run();return NextResponse.json({ok:true,profile:await profile()})}catch(error){console.error("member-profile:update",error);return NextResponse.json({error:"Could not save profile"},{status:503})}}
