"use client";

import { useEffect, useState } from "react";
import { FileText, ImagePlus, Loader2, Newspaper, Pencil, PlayCircle, Plus, Save, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { defaultSiteContent,normalizeSiteContent,type ContentItem,type ContentKind,type SiteContent } from "@/src/data/siteContent";

const blank=(kind:ContentKind="article"):ContentItem=>({id:crypto.randomUUID(),kind,title:{th:"",en:""},excerpt:{th:"",en:""},body:{th:"",en:""},image:"",videoUrl:"",publishedAt:new Date().toISOString().slice(0,10),active:true,featured:false});
const kindLabel:Record<ContentKind,string>={article:"บทความ",news:"ข่าวสาร",clip:"คลิป"};

export function ContentAdmin(){
  const [content,setContent]=useState<SiteContent>(defaultSiteContent);const [draft,setDraft]=useState<ContentItem|null>(null);
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{fetch("/csa-admin/api/site-content",{cache:"no-store"}).then(r=>r.json()).then(d=>setContent(normalizeSiteContent(d.content))).finally(()=>setLoading(false))},[]);
  const persist=async(next:SiteContent)=>{setSaving(true);setMessage("");try{const r=await fetch("/csa-admin/api/site-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});const d=await r.json();if(!r.ok)throw new Error(d.error||"บันทึกไม่สำเร็จ");setContent(next);setDraft(null);setMessage("บันทึกและอัปเดตหน้า Customer UI แล้ว")}catch(e){setMessage(e instanceof Error?e.message:"บันทึกไม่สำเร็จ")}finally{setSaving(false)}};
  const saveDraft=()=>{if(!draft)return;if(!draft.title.th.trim()){setMessage("กรุณากรอกชื่อภาษาไทย");return}const exists=content.contentItems.some(x=>x.id===draft.id);void persist({...content,contentItems:exists?content.contentItems.map(x=>x.id===draft.id?draft:x):[draft,...content.contentItems]})};
  const remove=(id:string)=>{if(!window.confirm("ลบรายการนี้ออกจากระบบหรือไม่?"))return;void persist({...content,contentItems:content.contentItems.filter(x=>x.id!==id)})};
  const toggle=(item:ContentItem)=>void persist({...content,contentItems:content.contentItems.map(x=>x.id===item.id?{...x,active:!x.active}:x)});
  const upload=async(file?:File)=>{if(!file||!draft)return;const allowed=["image/png","image/jpeg","image/webp","image/svg+xml"];if(!allowed.includes(file.type)||file.size>8*1024*1024){setMessage("ไฟล์ต้องเป็น PNG, JPG, WEBP หรือ SVG และไม่เกิน 8 MB");return}setUploading(true);try{const form=new FormData();form.append("file",file);const r=await fetch("/csa-admin/api/upload",{method:"POST",body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||"อัปโหลดไม่สำเร็จ");setDraft({...draft,image:d.url});setMessage("อัปโหลดรูปแล้ว กดบันทึกรายการเพื่อเผยแพร่")}catch(e){setMessage(e instanceof Error?e.message:"อัปโหลดไม่สำเร็จ")}finally{setUploading(false)}};
  if(loading)return <div className="grid h-64 place-items-center"><Loader2 className="animate-spin text-[#ffc400]"/></div>;
  return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold tracking-[.18em] text-[#ffc400]">CUSTOMER CONTENT</p><h2 className="mt-1 text-3xl font-black">บทความ ข่าวสาร และคลิป</h2><p className="mt-2 text-sm text-zinc-500">รายการที่เปิดใช้งานจะแสดงในเมนู Customer UI โดยอัตโนมัติ</p></div><Button onClick={()=>setDraft(blank())} className="rounded-xl bg-[#ffc400] text-black hover:bg-[#ffd43b]"><Plus/>เพิ่มรายการใหม่</Button></div>
    <div className="mt-5 grid gap-4 md:grid-cols-3">{(["article","news","clip"] as ContentKind[]).map(kind=>{const Icon=kind==="article"?FileText:kind==="news"?Newspaper:PlayCircle;const count=content.contentItems.filter(x=>x.kind===kind&&x.active).length;return <div key={kind} className="rounded-2xl border border-white/10 bg-[#111] p-5"><Icon className="text-[#ffc400]"/><p className="mt-4 text-sm text-zinc-500">{kindLabel[kind]}ที่กำลังแสดง</p><p className="mt-1 text-3xl font-black">{count}</p></div>})}</div>
    {draft&&<section className="mt-5 rounded-2xl border border-[#ffc400]/40 bg-[#111] p-5"><div className="flex items-center justify-between"><h3 className="text-xl font-black">{content.contentItems.some(x=>x.id===draft.id)?"แก้ไขรายการ":"เพิ่มรายการใหม่"}</h3><button onClick={()=>setDraft(null)} className="text-sm text-zinc-400">ปิด</button></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div><Label>ประเภท</Label><select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as ContentKind})} className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-black/40 px-3"><option value="article">บทความ</option><option value="news">ข่าวสาร</option><option value="clip">คลิป</option></select></div><Field label="วันที่เผยแพร่" type="date" value={draft.publishedAt} set={publishedAt=>setDraft({...draft,publishedAt})}/><Pair label="หัวข้อ" value={draft.title} set={title=>setDraft({...draft,title})}/><Pair label="คำโปรย" value={draft.excerpt} set={excerpt=>setDraft({...draft,excerpt})}/><div className="lg:col-span-2"><Pair area label="เนื้อหา" value={draft.body} set={body=>setDraft({...draft,body})}/></div><Field label="ลิงก์วิดีโอ (สำหรับคลิป)" value={draft.videoUrl} set={videoUrl=>setDraft({...draft,videoUrl})}/><Field label="URL รูปภาพ" value={draft.image} set={image=>setDraft({...draft,image})}/><div className="lg:col-span-2 flex flex-wrap items-center gap-4"><label className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-xl bg-[#ffc400] px-4 py-2 text-sm font-black text-black">{uploading?<Loader2 className="animate-spin"/>:<ImagePlus/>}เลือกรูปจากเครื่อง<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" className="hidden" onChange={e=>void upload(e.target.files?.[0])}/></label>{draft.image&&<img src={draft.image} alt="" className="h-20 w-32 rounded-xl object-cover"/>}<label className="flex items-center gap-2"><Switch checked={draft.active} onCheckedChange={active=>setDraft({...draft,active})}/>แสดงบนเว็บไซต์</label><label className="flex items-center gap-2"><Switch checked={draft.featured} onCheckedChange={featured=>setDraft({...draft,featured})}/>ปักหมุด</label></div></div><Button onClick={saveDraft} disabled={saving} className="mt-5 rounded-xl bg-[#ffc400] text-black hover:bg-[#ffd43b]">{saving?<Loader2 className="animate-spin"/>:<Save/>}บันทึกรายการ</Button></section>}
    <section className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-[#111]">{content.contentItems.length===0?<div className="p-10 text-center text-zinc-500">ยังไม่มีบทความ ข่าวสาร หรือคลิป กด “เพิ่มรายการใหม่” เพื่อเริ่มต้น</div>:content.contentItems.map(item=><article key={item.id} className="flex flex-wrap items-center gap-4 border-b border-white/10 p-4 last:border-0">{item.image?<img src={item.image} alt="" className="h-16 w-24 rounded-lg object-cover"/>:<span className="grid h-16 w-24 place-items-center rounded-lg bg-black text-zinc-600"><FileText/></span>}<div className="min-w-48 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#ffc400] px-2.5 py-1 text-[11px] font-black text-black">{kindLabel[item.kind]}</span><span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${item.active?"bg-emerald-500/15 text-emerald-400":"bg-red-500/15 text-red-400"}`}>{item.active?"กำลังแสดง":"ซ่อนอยู่"}</span></div><h3 className="mt-2 font-black">{item.title.th||"(ไม่มีชื่อ)"}</h3><p className="text-xs text-zinc-500">{item.publishedAt}</p></div><div className="flex gap-2"><Button onClick={()=>toggle(item)} variant="outline" className="rounded-xl border-white/15 bg-transparent text-white">{item.active?"ซ่อน":"แสดง"}</Button><Button onClick={()=>setDraft(item)} className="rounded-xl bg-[#ffc400] text-black hover:bg-[#ffd43b]"><Pencil/></Button><Button onClick={()=>remove(item.id)} variant="outline" className="rounded-xl border-red-500/30 bg-transparent text-red-400"><Trash2/></Button></div></article>)}</section>{message&&<p className={`mt-4 font-bold ${message.includes("สำเร็จ")||message.includes("แล้ว")?"text-emerald-400":"text-red-400"}`}>{message}</p>}</div>;
}

function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <div><Label>{label}</Label><Input type={type} value={value} onChange={e=>set(e.target.value)} className="mt-2 border-white/15 bg-black/40"/></div>}
function Pair({label,value,set,area}:{label:string;value:{th:string;en:string};set:(v:{th:string;en:string})=>void;area?:boolean}){const C=area?Textarea:Input;return <div><Label>{label}</Label><div className="mt-2 grid gap-2 sm:grid-cols-2"><C value={value.th} onChange={e=>set({...value,th:e.target.value})} placeholder="ภาษาไทย" className="border-white/15 bg-black/40"/><C value={value.en} onChange={e=>set({...value,en:e.target.value})} placeholder="English" className="border-white/15 bg-black/40"/></div></div>}
