"use client";

import { useState } from "react";
import { BarChart3, BellRing, Boxes, CreditCard, FileText, Globe2, History, LayoutDashboard, MapPin, Menu, Newspaper, PackageCheck, Send, ShieldCheck, ShoppingBag, Tags, Truck, Users, Wrench, X } from "lucide-react";
import type { Lang } from "@/src/types/portal";
import { ProductAdmin } from "@/src/components/ProductAdmin";
import { WebsiteAdmin } from "@/src/components/WebsiteAdmin";
import { ContentAdmin } from "@/src/components/ContentAdmin";
import { SalesAdmin,type SalesModule } from "@/src/components/SalesAdmin";
import { OperationsAdmin,type OperationModule } from "@/src/components/OperationsAdmin";
import type { AdminPermission } from "@/app/admin-auth";

type Module=SalesModule|OperationModule|"product"|"website"|"content-manager";
type Group="sales"|"after_sales"|"analysis"|"content"|"security";
const modules:{id:Module;th:string;en:string;icon:typeof LayoutDashboard;group:Group}[]=[
  {id:"dashboard",th:"ภาพรวม",en:"Overview",icon:LayoutDashboard,group:"sales"},{id:"leads",th:"ผู้สนใจ",en:"Leads",icon:BarChart3,group:"sales"},{id:"customers",th:"ลูกค้า",en:"Customers",icon:Users,group:"sales"},{id:"quotes",th:"ใบเสนอราคา",en:"Quotations",icon:FileText,group:"sales"},{id:"orders",th:"คำสั่งซื้อ",en:"Orders",icon:ShoppingBag,group:"sales"},
  {id:"payments",th:"การชำระเงิน",en:"Payments",icon:CreditCard,group:"after_sales"},{id:"shipping",th:"การจัดส่ง",en:"Shipping",icon:Truck,group:"after_sales"},{id:"warranties",th:"รับประกัน",en:"Warranty",icon:ShieldCheck,group:"after_sales"},{id:"claims",th:"เคลม",en:"Claims",icon:Wrench,group:"after_sales"},{id:"serials",th:"Serial และ Lot",en:"Serial & Lot",icon:Tags,group:"after_sales"},{id:"dealers",th:"ตัวแทนจำหน่าย",en:"Dealers",icon:MapPin,group:"after_sales"},
  {id:"reports",th:"รายงานการขาย",en:"Sales reports",icon:BarChart3,group:"analysis"},{id:"stock",th:"แจ้งเตือนสต็อก",en:"Stock alerts",icon:Boxes,group:"analysis"},{id:"reminders",th:"ติดตามลูกค้า",en:"Follow-ups",icon:BellRing,group:"analysis"},{id:"line",th:"แจ้งผ่าน LINE",en:"LINE notifications",icon:Send,group:"analysis"},
  {id:"product",th:"สินค้า",en:"Products",icon:PackageCheck,group:"content"},{id:"website",th:"เว็บไซต์",en:"Website",icon:Globe2,group:"content"},{id:"content-manager",th:"บทความและข่าวสาร",en:"Content",icon:Newspaper,group:"content"},{id:"roles",th:"ผู้ใช้งานและสิทธิ์",en:"Users & roles",icon:Users,group:"security"},{id:"audits",th:"ประวัติการใช้งาน",en:"Audit logs",icon:History,group:"security"},
];
const groupLabels:Record<Group,{th:string;en:string}>={sales:{th:"งานขาย",en:"Sales"},after_sales:{th:"หลังการขาย",en:"After-sales"},analysis:{th:"วิเคราะห์และอัตโนมัติ",en:"Reports & automation"},content:{th:"สินค้าและเว็บไซต์",en:"Products & website"},security:{th:"ความปลอดภัย",en:"Security"}};
function permissionFor(module:Module):AdminPermission{if(["dashboard","leads","customers","quotes","orders","reminders"].includes(module))return "sales";if(["payments","shipping","warranties","claims","serials","dealers","line"].includes(module))return "after_sales";if(["reports"].includes(module))return "reports";if(["product","stock"].includes(module))return "inventory";if(["website","content-manager"].includes(module))return "content";return "roles"}

export function InternalSystem({lang,userEmail,permissions}:{lang:Lang;userEmail:string;permissions:AdminPermission[]}){
  const available=modules.filter(item=>permissions.includes(permissionFor(item.id)));
  const [active,setActive]=useState<Module>(available[0]?.id??"dashboard");const [menuOpen,setMenuOpen]=useState(false);
  const navigate=(next:Module)=>{setActive(next);setMenuOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
  const isSales=(value:Module):value is SalesModule=>["dashboard","leads","customers","quotes","orders"].includes(value);
  const isOperations=(value:Module):value is OperationModule=>!["dashboard","leads","customers","quotes","orders","product","website","content-manager"].includes(value);
  return <div className="min-h-[100dvh] overflow-x-clip bg-[#080808] text-white"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#0b0b0b]/95 px-4 py-3 backdrop-blur md:px-6"><div className="mx-auto flex max-w-[1700px] items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><button onClick={()=>setMenuOpen(x=>!x)} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-white/10 lg:hidden" aria-label={lang==="th"?"เปิดเมนู":"Open menu"}>{menuOpen?<X/>:<Menu/>}</button><div className="min-w-0"><p className="text-[11px] font-black tracking-[.2em] text-[#ffc400]">CSA BACK-OFFICE</p><h1 className="truncate text-lg font-black sm:text-xl">{lang==="th"?"ระบบจัดการ CSA":"CSA Management"}</h1></div></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="max-w-56 truncate text-sm font-bold">{userEmail}</p><p className="flex items-center justify-end gap-1.5 text-xs font-bold text-emerald-400"><span className="h-2 w-2 rounded-full bg-emerald-400"/>{lang==="th"?"พร้อมใช้งาน":"Online"}</p></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-[#ffc400] bg-[#ffc400] text-sm font-black text-black">CSA</span></div></div></header><div className="mx-auto grid max-w-[1700px] lg:grid-cols-[260px_1fr]"><aside className={`${menuOpen?"block":"hidden"} fixed inset-x-0 top-[69px] z-30 max-h-[calc(100dvh-69px)] overflow-y-auto border-b border-white/10 bg-[#0d0d0d] p-3 pb-[calc(1rem+env(safe-area-inset-bottom))] lg:sticky lg:top-[69px] lg:block lg:h-[calc(100dvh-69px)] lg:border-b-0 lg:border-r`}>{(["sales","after_sales","analysis","content","security"] as Group[]).map(group=><NavGroup key={group} title={groupLabels[group][lang]} items={available.filter(x=>x.group===group)} active={active} navigate={navigate} lang={lang}/>)}</aside><main className="min-w-0 p-4 pb-[calc(2rem+env(safe-area-inset-bottom))] md:p-7">{active==="product"?<ProductAdmin/>:active==="website"?<WebsiteAdmin/>:active==="content-manager"?<ContentAdmin/>:isSales(active)?<SalesAdmin module={active} onNavigate={navigate}/>:isOperations(active)?<OperationsAdmin module={active}/>:null}</main></div></div>;
}
function NavGroup({title,items,active,navigate,lang}:{title:string;items:typeof modules;active:Module;navigate:(m:Module)=>void;lang:Lang}){return <div className="mb-5"><p className="px-3 pb-2 text-[11px] font-bold uppercase tracking-widest text-zinc-600">{title}</p><nav className="space-y-1">{items.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>navigate(item.id)} className={`flex min-h-11 w-full items-center gap-3 rounded-xl border px-3 text-left text-sm font-bold transition ${active===item.id?"border-[#ffc400] bg-[#ffc400] text-black":"border-transparent text-zinc-400 hover:bg-white/5 hover:text-white"}`}><Icon className="h-4 w-4 shrink-0"/><span className="flex-1">{item[lang]}</span></button>})}</nav></div>}
