"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, BellRing, Boxes, CheckCircle2, ClipboardCheck, FileClock, FileImage, History, Loader2, MapPin, PackageCheck, Plus, Receipt, Search, Send, ShieldCheck, ShoppingBag, Truck, Users, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { Product } from "@/src/types/portal";

export type OperationModule="reports"|"payments"|"shipping"|"warranties"|"claims"|"serials"|"dealers"|"stock"|"reminders"|"line"|"roles"|"audits";
type Kind="payment"|"shipment"|"warranty"|"claim"|"serial"|"dealer"|"notification";
type Data=Record<string,string|number|boolean|undefined>;
type RecordItem={id:string;kind:Kind;status:string;data:Data;created_at:string;updated_at:string};
type SalesRecord={id:string;kind:"lead"|"customer"|"quote"|"order";status:string;data:Data;created_at:string;updated_at:string};
type RoleItem={email:string;role:string;permissions:string[];active:boolean;updated_at:string};
type AuditItem={id:string;email:string;action:string;entity:string;entity_id:string;detail_json:string;created_at:string};
type FormState={id?:string;kind:Exclude<Kind,"notification">;status:string;data:Data};

const money=new Intl.NumberFormat("th-TH",{style:"currency",currency:"THB",maximumFractionDigits:0});
const moduleKind:Partial<Record<OperationModule,Exclude<Kind,"notification">>>={payments:"payment",shipping:"shipment",warranties:"warranty",claims:"claim",serials:"serial",dealers:"dealer"};
const meta:Record<Exclude<Kind,"notification">,{title:string;eyebrow:string;description:string;icon:typeof Receipt;statuses:{value:string;label:string}[]}>= {
  payment:{title:"หลักฐานการชำระเงิน",eyebrow:"PAYMENT EVIDENCE",description:"ตรวจสอบสลิป ยอดชำระ และเชื่อมกับออเดอร์",icon:Receipt,statuses:[{value:"pending",label:"รอตรวจสอบ"},{value:"verified",label:"ยืนยันแล้ว"},{value:"rejected",label:"ไม่ผ่าน"}]},
  shipment:{title:"การจัดส่งและ Tracking",eyebrow:"SHIPPING",description:"บันทึกขนส่ง เลขติดตาม และกำหนดส่ง",icon:Truck,statuses:[{value:"packing",label:"กำลังแพ็ก"},{value:"shipped",label:"จัดส่งแล้ว"},{value:"delivered",label:"ส่งสำเร็จ"},{value:"returned",label:"ตีกลับ"}]},
  warranty:{title:"การรับประกัน",eyebrow:"WARRANTY",description:"ลงทะเบียนและตรวจสอบสิทธิ์รับประกันจาก Serial",icon:ShieldCheck,statuses:[{value:"active",label:"ใช้งาน"},{value:"expired",label:"หมดอายุ"},{value:"void",label:"ยกเลิก"}]},
  claim:{title:"เคลมสินค้า",eyebrow:"CLAIMS",description:"รับเรื่อง ตรวจสอบ อนุมัติ และติดตามผลเคลม",icon:Wrench,statuses:[{value:"received",label:"รับเรื่อง"},{value:"reviewing",label:"กำลังตรวจสอบ"},{value:"approved",label:"อนุมัติ"},{value:"rejected",label:"ไม่อนุมัติ"},{value:"completed",label:"เสร็จสิ้น"}]},
  serial:{title:"Serial / Lot",eyebrow:"SERIAL & LOT",description:"ผูกหมายเลขประจำสินค้ากับ Lot และสถานะ",icon:Boxes,statuses:[{value:"available",label:"พร้อมใช้"},{value:"sold",label:"ขายแล้ว"},{value:"registered",label:"ลงทะเบียนแล้ว"},{value:"void",label:"ยกเลิก"}]},
  dealer:{title:"ตัวแทนจำหน่าย",eyebrow:"DEALER MANAGEMENT",description:"จัดการข้อมูลติดต่อ พื้นที่บริการ และสถานะตัวแทน",icon:MapPin,statuses:[{value:"active",label:"เปิดใช้งาน"},{value:"pending",label:"รอตรวจสอบ"},{value:"inactive",label:"ปิดใช้งาน"}]},
};
const permissions=[{id:"sales",label:"งานขาย"},{id:"after_sales",label:"หลังการขาย"},{id:"inventory",label:"สินค้าและสต็อก"},{id:"content",label:"เว็บไซต์"},{id:"reports",label:"รายงาน"},{id:"roles",label:"ผู้ใช้และสิทธิ์"}];

export function OperationsAdmin({module}:{module:OperationModule}){
  const [records,setRecords]=useState<RecordItem[]>([]);const [sales,setSales]=useState<SalesRecord[]>([]);const [products,setProducts]=useState<Product[]>([]);
  const [roles,setRoles]=useState<RoleItem[]>([]);const [audits,setAudits]=useState<AuditItem[]>([]);const [lineConfigured,setLineConfigured]=useState(false);
  const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  const load=async()=>{setLoading(true);try{const [o,s,p]=await Promise.all([fetch("/csa-admin/api/operations",{cache:"no-store"}),fetch("/csa-admin/api/sales",{cache:"no-store"}),fetch("/csa-admin/api/products?includeInactive=1",{cache:"no-store"})]);const od=await o.json();const sd=await s.json();const pd=await p.json();if(!o.ok)throw new Error(od.error);setRecords(od.records??[]);setRoles(od.roles??[]);setAudits(od.audits??[]);setLineConfigured(Boolean(od.lineConfigured));if(s.ok)setSales(sd.records??[]);if(p.ok)setProducts(pd.products??[])}catch(error){setMessage(error instanceof Error?error.message:"โหลดข้อมูลไม่สำเร็จ")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const notify=async(text:string)=>{setMessage("กำลังส่งการแจ้งเตือน…");const r=await fetch("/csa-admin/api/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"notify",message:text})});const d=await r.json();if(r.ok){setMessage(d.delivery==="sent"?"ส่ง LINE เรียบร้อย":"บันทึกเข้าคิวแล้ว กรุณาตั้งค่า LINE token และปลายทาง");await load()}else setMessage(d.error||"ส่งไม่สำเร็จ")};
  if(loading)return <div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-[#ffc400]"/></div>;
  const kind=moduleKind[module];
  return <div>{message&&<p className="mb-4 rounded-xl border border-[#ffc400]/20 bg-[#ffc400]/5 px-4 py-3 text-sm font-bold text-[#ffc400]">{message}</p>}{kind?<RecordsPanel kind={kind} records={records.filter(x=>x.kind===kind)} reload={load} setMessage={setMessage}/>:module==="reports"?<Reports sales={sales} records={records}/>:module==="stock"?<Stock products={products}/>:module==="reminders"?<Reminders sales={sales} notify={notify}/>:module==="line"?<LinePanel records={records.filter(x=>x.kind==="notification")} configured={lineConfigured} notify={notify}/>:module==="roles"?<Roles roles={roles} reload={load} setMessage={setMessage}/>:<Audits audits={audits}/>}</div>;
}

function RecordsPanel({kind,records,reload,setMessage}:{kind:Exclude<Kind,"notification">;records:RecordItem[];reload:()=>Promise<void>;setMessage:(v:string)=>void}){
  const [query,setQuery]=useState("");const [form,setForm]=useState<FormState|null>(null);const [saving,setSaving]=useState(false);const config=meta[kind];const Icon=config.icon;
  const items=useMemo(()=>records.filter(x=>`${x.id} ${Object.values(x.data).join(" ")}`.toLowerCase().includes(query.toLowerCase())),[records,query]);
  const save=async()=>{if(!form)return;setSaving(true);const r=await fetch("/csa-admin/api/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(r.ok){setForm(null);setMessage("บันทึกข้อมูลเรียบร้อย");await reload()}else setMessage(d.error||"บันทึกไม่สำเร็จ");setSaving(false)};
  const remove=async(item:RecordItem)=>{if(!window.confirm(`ลบ ${item.id}?`))return;const r=await fetch("/csa-admin/api/operations",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id})});if(r.ok){setMessage("ลบรายการแล้ว");await reload()}else setMessage("ลบรายการไม่สำเร็จ")};
  const create=()=>setForm({kind,status:config.statuses[0].value,data:kind==="serial"?{serial:serialSuggestion(),lot:lotSuggestion()}: {}});
  return <div><Header eyebrow={config.eyebrow} title={config.title} description={config.description} action={<Button onClick={create} className="bg-white text-black hover:bg-zinc-200"><Plus/>เพิ่มรายการ</Button>}/><div className="mt-5 flex min-h-12 items-center rounded-xl border border-white/15 bg-[#111] px-4"><Search className="mr-3 h-4 w-4 text-zinc-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาเลขรายการ ลูกค้า Serial หรือ Tracking" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/><span className="text-xs text-zinc-600">{items.length} รายการ</span></div><div className="mt-4 space-y-3">{items.map(item=><article key={item.id} className="grid gap-4 rounded-2xl border border-white/10 bg-[#111] p-4 lg:grid-cols-[1fr_auto] lg:items-center"><button onClick={()=>setForm({id:item.id,kind,status:item.status,data:{...item.data}})} className="min-w-0 text-left"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-[#ffc400]"/><span className="font-mono text-xs font-bold text-[#ffc400]">{item.id}</span><Status value={item.status} labels={config.statuses}/></div><h3 className="mt-2 text-lg font-black">{primary(kind,item.data)}</h3><p className="mt-1 text-sm text-zinc-500">{secondary(kind,item.data)}</p></button><div className="flex gap-2"><Button onClick={()=>setForm({id:item.id,kind,status:item.status,data:{...item.data}})} variant="outline" className="border-white/15 bg-transparent text-white">แก้ไข</Button><Button onClick={()=>void remove(item)} variant="outline" className="border-red-500/20 bg-transparent text-red-400">ลบ</Button></div></article>)}{!items.length&&<Empty icon={Icon} text="ยังไม่มีข้อมูลในส่วนนี้" action={create}/>}</div><OperationDialog form={form} setForm={setForm} saving={saving} save={()=>void save()}/></div>;
}

function OperationDialog({form,setForm,saving,save}:{form:FormState|null;setForm:(v:FormState|null)=>void;saving:boolean;save:()=>void}){if(!form)return null;const config=meta[form.kind];const d=form.data;const set=(key:string,value:string|number|boolean)=>setForm({...form,data:{...d,[key]:value}});return <Dialog open onOpenChange={open=>!open&&setForm(null)}><DialogContent className="flex h-[100dvh] max-h-[100dvh] flex-col overflow-hidden rounded-none border-white/10 bg-[#121212] p-0 text-white sm:h-auto sm:max-h-[92dvh] sm:max-w-3xl sm:rounded-2xl"><DialogHeader className="border-b border-white/10 px-5 py-4"><DialogTitle className="text-2xl font-black">{form.id?"แก้ไข":"เพิ่ม"}{config.title}</DialogTitle><p className="font-mono text-xs text-[#ffc400]">{form.id||"เลขรายการสร้างอัตโนมัติ"}</p></DialogHeader><div className="min-h-0 flex-1 overflow-y-auto p-5"><div className="grid gap-4 sm:grid-cols-2">{fields(form.kind).map(field=><Field key={field.key} label={field.label} type={field.type} value={String(d[field.key]??"")} onChange={value=>set(field.key,field.type==="number"?Number(value):value)} area={field.area}/>)}</div>{form.kind==="payment"&&<EvidenceUpload value={String(d.evidenceUrl||"")} set={value=>set("evidenceUrl",value)}/>}<div className="mt-5"><Label>สถานะ</Label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-2 min-h-11 w-full rounded-xl border border-white/15 bg-black px-3 text-sm">{config.statuses.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></div></div><div className="flex shrink-0 justify-end gap-2 border-t border-white/10 bg-[#0d0d0d] px-4 pt-4 pb-[calc(1rem+env(safe-area-inset-bottom))]"><Button onClick={()=>setForm(null)} variant="outline" className="border-white/15 bg-transparent text-white">ยกเลิก</Button><Button onClick={save} disabled={saving} className="bg-white text-black hover:bg-zinc-200">{saving&&<Loader2 className="animate-spin"/>}บันทึก</Button></div></DialogContent></Dialog>}

function EvidenceUpload({value,set}:{value:string;set:(v:string)=>void}){const [busy,setBusy]=useState(false);const upload=async(file?:File)=>{if(!file)return;setBusy(true);const form=new FormData();form.append("file",file);const r=await fetch("/csa-admin/api/upload",{method:"POST",body:form});const d=await r.json();if(r.ok&&d.url)set(String(d.url));setBusy(false)};return <div className="mt-5 rounded-xl border border-white/10 p-4"><Label>หลักฐานการชำระเงิน</Label><div className="mt-3 flex flex-wrap items-center gap-3">{value?<img src={value} alt="หลักฐานการชำระเงิน" className="h-24 w-24 rounded-xl bg-white object-contain"/>:<span className="grid h-24 w-24 place-items-center rounded-xl bg-black"><FileImage className="text-zinc-500"/></span>}<label className={`inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-black text-black ${busy?"pointer-events-none opacity-60":"cursor-pointer"}`}>{busy?<Loader2 className="animate-spin"/>:<FileImage/>}{busy?"กำลังอัปโหลด":"อัปโหลดสลิป"}<input type="file" accept="image/*" disabled={busy} className="hidden" onChange={e=>{void upload(e.target.files?.[0]);e.currentTarget.value=""}}/></label></div></div>}

function Reports({sales,records}:{sales:SalesRecord[];records:RecordItem[]}){const orders=sales.filter(x=>x.kind==="order");const paid=orders.filter(x=>["paid","packing","shipped","completed"].includes(x.status));const revenue=paid.reduce((sum,x)=>sum+Number(x.data.amount||0),0);const quotes=sales.filter(x=>x.kind==="quote");const won=quotes.filter(x=>x.status==="won").length;const claims=records.filter(x=>x.kind==="claim");const months=new Map<string,number>();paid.forEach(x=>{const key=x.created_at.slice(0,7);months.set(key,(months.get(key)||0)+Number(x.data.amount||0))});return <div><Header eyebrow="SALES ANALYTICS" title="รายงานการขาย" description="ยอดขาย Conversion และงานหลังการขายจากข้อมูลจริง"/><div className="mt-5 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric icon={ShoppingBag} label="ออเดอร์ทั้งหมด" value={String(orders.length)}/><Metric icon={BarChart3} label="ยอดขายชำระแล้ว" value={money.format(revenue)}/><Metric icon={CheckCircle2} label="Quotation conversion" value={`${quotes.length?Math.round(won/quotes.length*100):0}%`}/><Metric icon={Wrench} label="เคลมที่เปิดอยู่" value={String(claims.filter(x=>!["completed","rejected"].includes(x.status)).length)}/></div><section className="mt-5 rounded-2xl border border-white/10 bg-[#111] p-5"><h3 className="font-black">ยอดขายรายเดือน</h3><div className="mt-5 space-y-4">{[...months.entries()].sort().reverse().map(([month,value])=><div key={month}><div className="flex justify-between text-sm"><span>{month}</span><strong>{money.format(value)}</strong></div><div className="mt-2 h-2 rounded-full bg-white/5"><div className="h-2 rounded-full bg-[#ffc400]" style={{width:`${Math.max(4,Math.min(100,revenue?value/revenue*100:0))}%`}}/></div></div>)}{!months.size&&<p className="text-sm text-zinc-500">ยังไม่มีออเดอร์ที่ชำระแล้ว</p>}</div></section></div>}

function Stock({products}:{products:Product[]}){const low=products.filter(x=>x.active!==false&&Number(x.stock||0)<=5).sort((a,b)=>Number(a.stock||0)-Number(b.stock||0));return <div><Header eyebrow="STOCK ALERTS" title="แจ้งเตือนสต็อก" description="สินค้าที่เหลือ 5 ชิ้นหรือน้อยกว่า ควรเติมสต็อกก่อนขายขาด"/><div className="mt-5 grid grid-cols-2 gap-3"><Metric icon={Boxes} label="สินค้าที่กำลังแสดง" value={String(products.filter(x=>x.active!==false).length)}/><Metric icon={AlertTriangle} label="สต็อกต่ำ" value={String(low.length)}/></div><section className="mt-5 overflow-x-auto rounded-2xl border border-white/10 bg-[#111]"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-xs text-zinc-500"><tr><th className="p-4">SKU</th><th>สินค้า</th><th>รุ่นรถ</th><th>คงเหลือ</th><th>สถานะ</th></tr></thead><tbody>{low.map(x=><tr key={x.id} className="border-t border-white/10"><td className="p-4 font-mono text-[#ffc400]">{x.id}</td><td className="font-bold">{x.name}</td><td>{x.model||"—"}</td><td className="text-xl font-black">{x.stock||0}</td><td><span className="rounded-full bg-red-500/15 px-2 py-1 text-xs font-bold text-red-400">ต้องเติมสต็อก</span></td></tr>)}</tbody></table>{!low.length&&<div className="p-10 text-center text-sm text-zinc-500">สต็อกอยู่ในระดับปกติ</div>}</section></div>}

function Reminders({sales,notify}:{sales:SalesRecord[];notify:(text:string)=>Promise<void>}){const today=new Date().toISOString().slice(0,10);const due=sales.filter(x=>x.kind==="lead"&&!['won','lost'].includes(x.status)&&String(x.data.nextFollowUp||"")<=today).sort((a,b)=>String(a.data.nextFollowUp).localeCompare(String(b.data.nextFollowUp)));return <div><Header eyebrow="FOLLOW-UP REMINDERS" title="รายการติดตาม" description="Lead ที่ถึงกำหนดหรือล่าช้า พร้อมส่งเตือนทีมทาง LINE" action={<Button onClick={()=>void notify(`CSA: มี Lead ถึงกำหนดติดตาม ${due.length} รายการ`)} disabled={!due.length} className="bg-white text-black hover:bg-zinc-200"><BellRing/>แจ้งเตือนทีม</Button>}/><div className="mt-5 space-y-3">{due.map(x=><article key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-[#111] p-4"><div><span className="font-mono text-xs text-[#ffc400]">{x.id}</span><h3 className="mt-1 font-black">{String(x.data.name||"ไม่ระบุชื่อ")}</h3><p className="text-sm text-zinc-500">{String(x.data.phone||"—")} · นัดติดตาม {String(x.data.nextFollowUp||"ไม่ระบุ")}</p></div><Button onClick={()=>void notify(`ติดตามลูกค้า ${String(x.data.name||"")} ${String(x.data.phone||"")} · ${String(x.data.product||"")} · กำหนด ${String(x.data.nextFollowUp||today)}`)} variant="outline" className="border-white/15 bg-transparent text-white"><Send/>ส่ง LINE</Button></article>)}{!due.length&&<Empty icon={CheckCircle2} text="ไม่มีรายการติดตามค้าง"/>}</div></div>}

function LinePanel({records,configured,notify}:{records:RecordItem[];configured:boolean;notify:(text:string)=>Promise<void>}){const [text,setText]=useState("");return <div><Header eyebrow="LINE NOTIFICATION" title="แจ้งเตือนผ่าน LINE" description="ส่งข้อความถึงกลุ่มหรือผู้รับที่กำหนด และเก็บประวัติการส่ง"/><div className={`mt-5 rounded-xl border p-4 ${configured?"border-emerald-500/20 bg-emerald-500/5":"border-amber-500/20 bg-amber-500/5"}`}><p className="font-bold">{configured?"● เชื่อมต่อ LINE แล้ว":"● ยังไม่ได้ตั้งค่า LINE token และปลายทาง"}</p><p className="mt-1 text-xs text-zinc-500">หากยังไม่เชื่อมต่อ ระบบจะเก็บข้อความไว้ในคิวโดยไม่ทำข้อมูลสูญหาย</p></div><section className="mt-5 rounded-2xl border border-white/10 bg-[#111] p-5"><Label>ข้อความแจ้งเตือน</Label><Textarea value={text} onChange={e=>setText(e.target.value)} placeholder="พิมพ์ข้อความที่ต้องการส่งให้ทีม" className="mt-2 min-h-36 border-white/15 bg-black/40"/><Button onClick={()=>{void notify(text);setText("")}} disabled={!text.trim()} className="mt-3 bg-white text-black hover:bg-zinc-200"><Send/>ส่งข้อความ</Button></section><section className="mt-5 space-y-2">{records.slice(0,20).map(x=><div key={x.id} className="rounded-xl border border-white/10 bg-[#111] p-4"><div className="flex justify-between"><span className="font-mono text-xs text-[#ffc400]">{x.id}</span><Status value={x.status} labels={[{value:"sent",label:"ส่งแล้ว"},{value:"queued",label:"อยู่ในคิว"},{value:"failed",label:"ส่งไม่สำเร็จ"}]}/></div><p className="mt-2 text-sm">{String(x.data.message||"")}</p></div>)}</section></div>}

function Roles({roles,reload,setMessage}:{roles:RoleItem[];reload:()=>Promise<void>;setMessage:(v:string)=>void}){const [email,setEmail]=useState("");const [role,setRole]=useState("staff");const [active,setActive]=useState(true);const [selected,setSelected]=useState<string[]>(["sales"]);const save=async()=>{const r=await fetch("/csa-admin/api/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"role",email,role,active,permissions:selected})});const d=await r.json();if(r.ok){setMessage("บันทึกสิทธิ์ผู้ใช้แล้ว");setEmail("");await reload()}else setMessage(d.error||"บันทึกไม่สำเร็จ")};const edit=(x:RoleItem)=>{setEmail(x.email);setRole(x.role);setActive(x.active);setSelected(x.permissions)};return <div><Header eyebrow="ROLE PERMISSIONS" title="ผู้ใช้และสิทธิ์" description="กำหนดสิทธิ์รายอีเมลหลังผ่าน Cloudflare Access"/><section className="mt-5 rounded-2xl border border-white/10 bg-[#111] p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="อีเมล" value={email} onChange={setEmail}/><div><Label>บทบาท</Label><select value={role} onChange={e=>setRole(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-white/15 bg-black px-3"><option value="staff">Staff</option><option value="sales">Sales</option><option value="manager">Manager</option><option value="super_admin">Super Admin</option></select></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{permissions.map(p=><label key={p.id} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-xl border border-white/10 px-3"><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(x=>x!==p.id))}/><span className="text-sm font-bold">{p.label}</span></label>)}</div><label className="mt-4 flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>อนุญาตให้ใช้งาน</label><Button onClick={()=>void save()} disabled={!email.includes("@")} className="mt-4 bg-white text-black hover:bg-zinc-200"><ShieldCheck/>บันทึกสิทธิ์</Button></section><div className="mt-5 space-y-3">{roles.map(x=><button key={x.email} onClick={()=>edit(x)} className="w-full rounded-xl border border-white/10 bg-[#111] p-4 text-left"><div className="flex flex-wrap justify-between gap-2"><strong>{x.email}</strong><span className={x.active?"text-emerald-400":"text-red-400"}>{x.active?"ACTIVE":"DISABLED"}</span></div><p className="mt-1 text-xs text-zinc-500">{x.role} · {x.permissions.join(", ")||"ไม่มีสิทธิ์"}</p></button>)}{!roles.length&&<p className="text-sm text-zinc-500">บัญชีหลักใช้สิทธิ์ Super Admin โดยอัตโนมัติ</p>}</div></div>}

function Audits({audits}:{audits:AuditItem[]}){return <div><Header eyebrow="AUDIT LOGS" title="ประวัติการใช้งาน" description="ตรวจสอบว่าใครแก้ไขอะไรและเมื่อใด"/><div className="mt-5 space-y-2">{audits.map(x=><article key={x.id} className="grid gap-2 rounded-xl border border-white/10 bg-[#111] p-4 sm:grid-cols-[180px_1fr_auto]"><div><p className="text-xs text-zinc-500">{new Date(`${x.created_at}Z`).toLocaleString("th-TH")}</p><p className="mt-1 truncate text-xs font-bold text-[#ffc400]">{x.email}</p></div><div><p className="font-bold">{x.action}</p><p className="text-xs text-zinc-500">{x.entity} · {x.entity_id||"—"}</p></div><History className="h-4 w-4 text-zinc-600"/></article>)}{!audits.length&&<Empty icon={History} text="ยังไม่มีประวัติการเปลี่ยนแปลง"/>}</div></div>}

function fields(kind:Exclude<Kind,"notification">){return {
  payment:[{key:"orderId",label:"เลขออเดอร์"},{key:"customer",label:"ลูกค้า"},{key:"amount",label:"ยอดชำระ",type:"number"},{key:"method",label:"ช่องทางชำระ"},{key:"paidAt",label:"วันที่ชำระ",type:"date"},{key:"note",label:"หมายเหตุ",area:true}],
  shipment:[{key:"orderId",label:"เลขออเดอร์"},{key:"customer",label:"ลูกค้า"},{key:"carrier",label:"บริษัทขนส่ง"},{key:"trackingNo",label:"Tracking number"},{key:"shippedAt",label:"วันที่ส่ง",type:"date"},{key:"eta",label:"กำหนดถึง",type:"date"}],
  warranty:[{key:"customer",label:"ลูกค้า"},{key:"phone",label:"เบอร์โทร"},{key:"product",label:"สินค้า"},{key:"serial",label:"Serial number"},{key:"purchaseDate",label:"วันที่ซื้อ",type:"date"},{key:"expiresAt",label:"หมดประกัน",type:"date"}],
  claim:[{key:"customer",label:"ลูกค้า"},{key:"phone",label:"เบอร์โทร"},{key:"warrantyId",label:"เลขประกัน"},{key:"serial",label:"Serial number"},{key:"receivedAt",label:"วันที่รับเรื่อง",type:"date"},{key:"issue",label:"อาการ / ปัญหา",area:true},{key:"resolution",label:"ผลการดำเนินการ",area:true}],
  serial:[{key:"serial",label:"Serial number"},{key:"lot",label:"Lot number"},{key:"product",label:"สินค้า / SKU"},{key:"producedAt",label:"วันที่ผลิต",type:"date"},{key:"orderId",label:"เลขออเดอร์"},{key:"note",label:"หมายเหตุ"}],
  dealer:[{key:"name",label:"ชื่อตัวแทน"},{key:"province",label:"จังหวัด"},{key:"phone",label:"เบอร์โทร"},{key:"line",label:"LINE"},{key:"contact",label:"ผู้ติดต่อ"},{key:"address",label:"ที่อยู่",area:true}],
}[kind] as {key:string;label:string;type?:string;area?:boolean}[]}
function primary(kind:Exclude<Kind,"notification">,d:Data){return String(kind==="serial"?d.serial:kind==="dealer"?d.name:d.customer||d.orderId||d.product||"ไม่ระบุ")}
function secondary(kind:Exclude<Kind,"notification">,d:Data){const keys=kind==="shipment"?["carrier","trackingNo","eta"]:kind==="payment"?["orderId","amount","method"]:kind==="dealer"?["province","phone","contact"]:kind==="serial"?["lot","product","orderId"]:["product","serial","phone"];return keys.map(k=>d[k]).filter(Boolean).join(" · ")||"เปิดเพื่อเพิ่มรายละเอียด"}
function lotSuggestion(){return new Date().toISOString().slice(0,10).replaceAll("-","")}
function serialSuggestion(){const now=new Date();return `${String(now.getUTCFullYear()).slice(2)}${String(now.getUTCMonth()+1).padStart(2,"0")} CSA `}
function Header({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black tracking-[.18em] text-[#ffc400]">{eyebrow}</p><h2 className="mt-1 text-3xl font-black">{title}</h2><p className="mt-2 text-sm text-zinc-500">{description}</p></div>{action}</div>}
function Metric({icon:Icon,label,value}:{icon:typeof Boxes;label:string;value:string}){return <article className="rounded-2xl border border-white/10 bg-[#111] p-4"><Icon className="h-5 w-5 text-[#ffc400]"/><p className="mt-5 text-2xl font-black sm:text-3xl">{value}</p><p className="mt-1 text-sm text-zinc-500">{label}</p></article>}
function Status({value,labels}:{value:string;labels:{value:string;label:string}[]}){return <span className="rounded-full bg-white/10 px-2 py-1 text-xs font-bold text-zinc-300">{labels.find(x=>x.value===value)?.label||value}</span>}
function Field({label,value,onChange,type="text",area}:{label:string;value:string;onChange:(v:string)=>void;type?:string;area?:boolean}){const C=area?Textarea:Input;return <div className={area?"sm:col-span-2":""}><Label>{label}</Label><C type={type} value={value} onChange={e=>onChange(e.target.value)} className={`mt-2 border-white/15 bg-black/40 ${area?"min-h-28":""}`}/></div>}
function Empty({icon:Icon,text,action}:{icon:typeof Boxes;text:string;action?:()=>void}){return <div className="grid min-h-52 place-items-center rounded-2xl border border-dashed border-white/10 text-center"><div><Icon className="mx-auto text-zinc-700"/><p className="mt-3 text-sm text-zinc-500">{text}</p>{action&&<Button onClick={action} className="mt-4 bg-white text-black hover:bg-zinc-200"><Plus/>เพิ่มรายการ</Button>}</div></div>}
