"use client";

import { useState } from "react";
import { Building2, CalendarDays, Car, ChevronDown, CircleHelp, Clock3, FileText, Heart, Mail, MapPin, Newspaper, PackageCheck, Phone, Play, Search, Send, ShieldCheck, ShoppingBag, Sparkles, UserRound, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { Lang, View } from "@/src/types/portal";

const copy = {
  th:{branches:"ค้นหาตัวแทนจำหน่าย",advice:"คำแนะนำจากผู้เชี่ยวชาญ",about:"เกี่ยวกับ CSA",news:"ข่าวสารและกิจกรรม",clips:"CSA Clips",faq:"คำถามที่พบบ่อย",careers:"ร่วมงานกับเรา",contact:"ติดต่อเรา",profile:"บัญชีของฉัน"},
  en:{branches:"Dealer locator",advice:"Expert advice",about:"About CSA",news:"News & events",clips:"CSA Clips",faq:"Frequently asked questions",careers:"Careers",contact:"Contact us",profile:"My account"}
};

function Page({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){
  return <div className="mx-auto max-w-7xl px-4 py-8 md:px-8 md:py-12"><p className="text-xs font-black tracking-[.2em] text-[#ffc400]">{eyebrow}</p><h1 className="mt-2 font-display text-4xl uppercase sm:text-6xl">{title}</h1><div className="mt-8">{children}</div></div>;
}

export function PublicPage({view,lang,go}:{view:View;lang:Lang;go:(v:View)=>void}){
  const c=copy[lang];
  if(view==="member"||view==="profile") return <ProfilePage lang={lang} go={go}/>;
  if(view==="my-products") return <MyProducts lang={lang} go={go}/>;
  if(view==="branches") return <Branches lang={lang}/>;
  if(view==="advice") return <Editorial lang={lang} mode="advice" title={c.advice}/>;
  if(view==="about") return <About lang={lang}/>;
  if(view==="news") return <Editorial lang={lang} mode="news" title={c.news}/>;
  if(view==="clips") return <Clips lang={lang}/>;
  if(view==="faq") return <Faq lang={lang}/>;
  if(view==="careers") return <Careers lang={lang}/>;
  return <Contact lang={lang}/>;
}

function ProfilePage({lang,go}:{lang:Lang;go:(v:View)=>void}){
  const [tab,setTab]=useState<"member"|"address"|"orders"|"favorites">("member");
  const tabs=[{id:"member",label:lang==="th"?"ข้อมูลสมาชิก":"Member",icon:UserRound},{id:"address",label:lang==="th"?"ที่อยู่":"Addresses",icon:MapPin},{id:"orders",label:lang==="th"?"คำสั่งซื้อ":"Orders",icon:ShoppingBag},{id:"favorites",label:lang==="th"?"รายการโปรด":"Favorites",icon:Heart}] as const;
  return <Page eyebrow="CSA MEMBER" title={copy[lang].profile}><div className="grid gap-5 lg:grid-cols-[250px_1fr]"><aside className="border border-white/10 bg-[#111] p-3">{tabs.map(t=>{const Icon=t.icon;return <button key={t.id} onClick={()=>setTab(t.id)} className={`flex w-full items-center gap-3 px-4 py-3 text-left text-sm font-bold ${tab===t.id?"bg-[#ffc400] text-black":"text-zinc-400 hover:bg-white/5"}`}><Icon className="h-4 w-4"/>{t.label}</button>})}</aside><section className="min-w-0 border border-white/10 bg-[#111] p-5 md:p-7">{tab==="member"&&<div><div className="flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-full bg-[#ffc400] text-xl font-black text-black">DM</span><div><h2 className="text-xl font-black">Demo Member</h2><p className="text-sm text-zinc-500">CSA Member · Since 2026</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><Field label={lang==="th"?"ชื่อ-นามสกุล":"Full name"} value="Demo Member"/><Field label={lang==="th"?"เบอร์โทร":"Phone"} value="000-000-0000"/><Field label="Email" value="demo@example.invalid"/><Field label={lang==="th"?"ประเภทธุรกิจ":"Customer type"} value="Retail customer"/></div><Button onClick={() => window.alert("Profile saved")} className="mt-5 bg-[#ffc400] text-black">{lang==="th"?"บันทึกข้อมูล":"Save profile"}</Button></div>}{tab==="address"&&<div><h2 className="text-xl font-black">{lang==="th"?"ที่อยู่จัดส่ง":"Shipping addresses"}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Address title="Home" text="Demo address, Thailand" primary/><Address title="Garage" text="Demo garage address"/></div><Button onClick={() => window.alert(lang==="th"?"พร้อมเพิ่มที่อยู่ใหม่":"Ready to add a new address")} variant="outline" className="mt-5 border-white/20 bg-transparent text-white">+ {lang==="th"?"เพิ่มที่อยู่":"Add address"}</Button></div>}{tab==="orders"&&<div><h2 className="text-xl font-black">{lang==="th"?"คำสั่งซื้อล่าสุด":"Recent orders"}</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="text-xs text-zinc-600"><tr><th className="pb-3">ORDER</th><th>DATE</th><th>TOTAL</th><th>STATUS</th></tr></thead><tbody>{[["DEMO-ORDER-001","Demo date","—","Shipped"],["DEMO-ORDER-002","Demo date","—","Delivered"]].map(r=><tr key={r[0]} className="border-t border-white/10"><td className="py-4 font-mono text-[#ffc400]">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td><span className="border border-white/10 px-2 py-1 text-xs">{r[3]}</span></td></tr>)}</tbody></table></div></div>}{tab==="favorites"&&<div><h2 className="text-xl font-black">{lang==="th"?"รายการโปรด":"Favorites"}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Favorite name="CSA Performance Front Pair" model="HIACE 300"/><Favorite name="CSA Comfort Rear Pair" model="MAJESTY"/></div></div>}</section></div></Page>;
}

function MyProducts({lang,go}:{lang:Lang;go:(v:View)=>void}){
  return <Page eyebrow="MY CSA" title={lang==="th"?"สินค้าของฉัน":"My products"}><div className="grid gap-4 lg:grid-cols-2"><article className="border border-[#ffc400]/30 bg-[#111] p-5"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center bg-[#ffc400] text-black"><Wrench/></span><span className="bg-emerald-500/15 px-2 py-1 text-xs font-bold text-emerald-400">WARRANTY ACTIVE</span></div><p className="mt-5 font-mono text-xs text-[#ffc400]">DEMO-SERIAL-001</p><h2 className="mt-1 text-xl font-black">CSA Performance Front Pair</h2><p className="mt-1 text-sm text-zinc-500">TOYOTA HIACE 300 · DEMO-LOT</p><div className="mt-6 grid grid-cols-2 border-t border-white/10 pt-4 text-sm"><div><p className="text-xs text-zinc-600">WARRANTY UNTIL</p><p className="mt-1 font-bold">20 Sep 2028</p></div><div><p className="text-xs text-zinc-600">CLAIMS</p><p className="mt-1 font-bold">0 open</p></div></div><Button onClick={()=>go("claims")} variant="outline" className="mt-5 border-white/20 bg-transparent text-white">{lang==="th"?"แจ้งเคลม":"Submit claim"}</Button></article><button onClick={()=>go("warranty")} className="min-h-64 border border-dashed border-white/20 p-6 text-left hover:border-[#ffc400]"><ShieldCheck className="h-7 w-7 text-[#ffc400]"/><h3 className="mt-4 text-xl font-black">{lang==="th"?"ลงทะเบียนสินค้าเพิ่ม":"Register another product"}</h3><p className="mt-2 text-sm text-zinc-500">{lang==="th"?"สแกน QR หรือกรอก Serial Number เพื่อเริ่มรับประกัน":"Scan QR or enter the serial number to activate warranty."}</p></button></div></Page>;
}

function Branches({lang}:{lang:Lang}){
  const [q,setQ]=useState(""); const all=[{name:"CSA Demo Service Point",place:"Demo district",phone:"000-000-0000"},{name:"Demo Dealer A",place:"Demo district",phone:"000-000-0000"},{name:"Demo Dealer B",place:"Demo district",phone:"000-000-0000"}]; const list=all.filter(x=>`${x.name} ${x.place}`.toLowerCase().includes(q.toLowerCase()));
  return <Page eyebrow="AUTHORIZED NETWORK" title={copy[lang].branches}><div className="grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><section><label className="flex h-12 items-center border border-white/15 bg-[#111] px-4"><Search className="mr-3 h-4 w-4 text-[#ffc400]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={lang==="th"?"ค้นหาจังหวัดหรือสาขา":"Search province or dealer"} className="w-full bg-transparent outline-none"/></label><div className="mt-3 space-y-3">{list.map((x,i)=><article key={x.name} className="border border-white/10 bg-[#111] p-4"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center bg-[#ffc400] text-sm font-black text-black">{i+1}</span><div><h2 className="font-bold">{x.name}</h2><p className="mt-1 text-sm text-zinc-500"><MapPin className="mr-1 inline h-3 w-3"/>{x.place}</p><a href={`tel:${x.phone}`} className="mt-2 block text-sm text-[#ffc400]">{x.phone}</a></div></div></article>)}</div></section><div className="relative min-h-[420px] overflow-hidden border border-white/10 bg-[#151515]"><div className="absolute inset-0 opacity-30" style={{backgroundImage:"linear-gradient(#333 1px,transparent 1px),linear-gradient(90deg,#333 1px,transparent 1px)",backgroundSize:"44px 44px"}}/><div className="absolute left-[35%] top-[35%] grid h-12 w-12 place-items-center rounded-full bg-[#ffc400] font-black text-black shadow-[0_0_0_12px_rgba(255,196,0,.13)]">1</div><div className="absolute left-[60%] top-[55%] grid h-10 w-10 place-items-center rounded-full bg-white font-black text-black">2</div><p className="absolute bottom-5 left-5 text-xs font-bold text-zinc-500">DEMO DEALER MAP · CHIANG MAI</p></div></div></Page>;
}

function Editorial({lang,mode,title}:{lang:Lang;mode:"advice"|"news";title:string}){
  const advice=["5 signs your van shocks need attention","How to choose suspension for passenger vans","Pre-trip suspension checklist"];
  const news=["CSA joins Chiang Mai Van Club Meeting 2026","New HIACE 300 fitment now available","CSA dealer training: September 2026"];
  const items=mode==="advice"?advice:news; const Icon=mode==="advice"?FileText:Newspaper;
  return <Page eyebrow={mode==="advice"?"KNOWLEDGE CENTER":"CSA UPDATE"} title={title}><div className="grid gap-4 md:grid-cols-3">{items.map((x,i)=><article key={x} className="group border border-white/10 bg-[#111] p-5"><div className="flex h-36 items-center justify-center bg-black"><Icon className="h-10 w-10 text-[#ffc400] transition group-hover:scale-110"/></div><p className="mt-5 text-xs font-bold text-[#ffc400]">{mode==="advice"?"CAR CARE":"NEWS"} · {21-i*4} SEP 2026</p><h2 className="mt-2 text-xl font-black leading-snug">{x}</h2><button onClick={() => window.alert(x)} className="mt-5 text-sm font-bold text-zinc-400 hover:text-white">{lang==="th"?"อ่านต่อ":"Read article"} →</button></article>)}</div></Page>;
}

function About({lang}:{lang:Lang}){
  return <Page eyebrow="ABOUT CSA" title={copy[lang].about}><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="border border-white/10 bg-[#111] p-6 md:p-9"><p className="text-2xl font-black leading-tight">{lang==="th"?"ช่วงล่างที่ออกแบบเพื่อรถตู้ และการใช้งานจริงของคนไทย":"Suspension engineered for vans and real Thai road conditions."}</p><p className="mt-5 leading-7 text-zinc-400">{lang==="th"?"CSA มุ่งพัฒนาผลิตภัณฑ์ช่วงล่างที่ให้ทั้งความนุ่ม ความมั่นคง และความมั่นใจ พร้อมระบบ Serial Number การรับประกัน และบริการหลังการขายที่ตรวจสอบได้":"CSA develops van suspension for comfort, stability and confidence, backed by traceable serial numbers, warranty and after-sales support."}</p></section><section className="grid grid-cols-2 gap-3">{[["3","VAN MODELS"],["24","DEALER PARTNERS"],["2 YRS","WARRANTY"],["100%","SERIAL TRACE"]].map(x=><div key={x[1]} className="border border-white/10 bg-[#ffc400] p-5 text-black"><p className="text-3xl font-black">{x[0]}</p><p className="mt-2 text-xs font-bold">{x[1]}</p></div>)}</section></div></Page>;
}

function Clips({lang}:{lang:Lang}){
  const [filter,setFilter]=useState("ALL"); const filters=["ALL","SHOP & TRAVEL","CAR CARE TIPS"];
  return <Page eyebrow="WATCH & LEARN" title={copy[lang].clips}><div className="mb-6 flex flex-wrap gap-2">{filters.map(x=><button key={x} onClick={()=>setFilter(x)} className={`border px-4 py-2 text-xs font-bold ${filter===x?"border-[#ffc400] bg-[#ffc400] text-black":"border-white/15"}`}>{x}</button>)}</div><div className="grid gap-4 md:grid-cols-3">{["HIACE 300 road test","Chiang Mai van weekend","Shock absorber care 101"].map((x,i)=><article key={x} className="border border-white/10 bg-[#111]"><div className="grid h-44 place-items-center bg-black"><span className="grid h-14 w-14 place-items-center rounded-full bg-[#ffc400] text-black"><Play className="ml-1"/></span></div><div className="p-5"><p className="text-xs font-bold text-[#ffc400]">{i===1?"SHOP & TRAVEL":"CAR CARE TIPS"}</p><h2 className="mt-2 text-lg font-black">{x}</h2><p className="mt-2 text-xs text-zinc-500"><Clock3 className="mr-1 inline h-3 w-3"/>04:{18+i*7}</p></div></article>)}</div></Page>;
}

function Faq({lang}:{lang:Lang}){
  const [open,setOpen]=useState(0); const items=lang==="th"?[["รับประกันนานเท่าไร?","ระยะเวลารับประกันตัวอย่าง 2 ปี นับจากวันที่ซื้อและลงทะเบียนสำเร็จ"],["Serial Number อยู่ตรงไหน?","ตรวจสอบได้บนฉลากสินค้า กล่องบรรจุภัณฑ์ หรือ QR ประจำชิ้นสินค้า"],["เคลมสินค้าอย่างไร?","เข้าสู่ระบบ เลือกสินค้าที่ลงทะเบียน อธิบายอาการ และแนบหลักฐาน"]]:[["How long is the warranty?","The demo warranty lasts two years from the verified purchase date."],["Where is the serial number?","Find it on the product label, packaging or product QR."],["How do I submit a claim?","Sign in, choose a registered product, describe the issue and attach evidence."]];
  return <Page eyebrow="SUPPORT" title={copy[lang].faq}><div className="mx-auto max-w-3xl space-y-3">{items.map((x,i)=><article key={x[0]} className="border border-white/10 bg-[#111]"><button onClick={()=>setOpen(open===i?-1:i)} className="flex w-full items-center justify-between p-5 text-left font-bold"><span><CircleHelp className="mr-3 inline h-5 w-5 text-[#ffc400]"/>{x[0]}</span><ChevronDown className={`h-4 w-4 transition ${open===i?"rotate-180":""}`}/></button>{open===i&&<p className="border-t border-white/10 px-5 py-4 leading-7 text-zinc-400">{x[1]}</p>}</article>)}</div></Page>;
}

function Careers({lang}:{lang:Lang}){
  return <Page eyebrow="JOIN CSA" title={copy[lang].careers}><div className="grid gap-4 lg:grid-cols-2">{[["Technical Sales – Van Segment","Chiang Mai · Full time"],["Customer Service & Warranty","Chiang Mai · Full time"]].map(x=><article key={x[0]} className="border border-white/10 bg-[#111] p-6"><Building2 className="h-6 w-6 text-[#ffc400]"/><h2 className="mt-5 text-xl font-black">{x[0]}</h2><p className="mt-2 text-sm text-zinc-500">{x[1]}</p><Button onClick={() => { window.location.href="mailto:careers@csa.co.th" }} variant="outline" className="mt-6 border-white/20 bg-transparent text-white">{lang==="th"?"ดูรายละเอียด":"View role"}</Button></article>)}</div></Page>;
}

function Contact({lang}:{lang:Lang}){
  const [sent,setSent]=useState(false); return <Page eyebrow="CONTACT CSA" title={copy[lang].contact}><div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><aside className="space-y-3">{[[Phone,"02-000-0000"],[Mail,"service@csa.co.th"],[MapPin,"Chiang Mai, Thailand"]].map(([I,t])=>{const Icon=I as typeof Phone;return <div key={t as string} className="flex items-center gap-4 border border-white/10 bg-[#111] p-5"><Icon className="h-5 w-5 text-[#ffc400]"/><span className="font-bold">{t as string}</span></div>})}</aside><section className="border border-white/10 bg-[#111] p-5 md:p-7">{sent?<div className="py-12 text-center"><PackageCheck className="mx-auto h-12 w-12 text-[#ffc400]"/><h2 className="mt-4 text-2xl font-black">{lang==="th"?"ส่งข้อความแล้ว":"Message sent"}</h2></div>:<div className="grid gap-4 sm:grid-cols-2"><Field label={lang==="th"?"ชื่อ":"Name"}/><Field label={lang==="th"?"เบอร์โทร":"Phone"}/><div className="sm:col-span-2"><Label>{lang==="th"?"ข้อความ":"Message"}</Label><Textarea className="mt-2 min-h-32 border-white/15 bg-black/40"/></div><Button onClick={()=>setSent(true)} className="bg-[#ffc400] text-black sm:col-span-2"><Send className="h-4 w-4"/>{lang==="th"?"ส่งข้อความ":"Send message"}</Button></div>}</section></div></Page>;
}

function Field({label,value}:{label:string;value?:string}){return <div><Label>{label}</Label><Input defaultValue={value} className="mt-2 border-white/15 bg-black/40"/></div>}
function Address({title,text,primary}:{title:string;text:string;primary?:boolean}){return <article className="border border-white/10 p-4"><div className="flex justify-between"><b>{title}</b>{primary&&<span className="text-xs font-bold text-[#ffc400]">PRIMARY</span>}</div><p className="mt-3 text-sm leading-6 text-zinc-500">{text}</p></article>}
function Favorite({name,model}:{name:string;model:string}){return <article className="border border-white/10 p-4"><Heart className="h-5 w-5 fill-[#ffc400] text-[#ffc400]"/><h3 className="mt-4 font-bold">{name}</h3><p className="mt-1 text-xs text-zinc-500">{model}</p></article>}
