"use client";

import { useEffect, useState } from "react";
import { Building2, CalendarDays, Car, ChevronDown, CircleHelp, Clock3, FileText, Heart, Mail, MapPin, Navigation, Newspaper, PackageCheck, Phone, Play, Search, Send, ShieldCheck, ShoppingBag, Sparkles, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ShockAbsorberIcon } from "@/src/components/icons/ShockAbsorberIcon";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { Lang, View } from "@/src/types/portal";
import type { SiteContent } from "@/src/data/siteContent";

const copy = {
  th:{branches:"ค้นหาตัวแทนจำหน่าย",advice:"คำแนะนำจากผู้เชี่ยวชาญ",about:"เกี่ยวกับ CSA",news:"ข่าวสารและกิจกรรม",clips:"CSA Clips",faq:"คำถามที่พบบ่อย",careers:"ร่วมงานกับเรา",contact:"ติดต่อเรา",profile:"บัญชีของฉัน"},
  en:{branches:"Dealer locator",advice:"Expert advice",about:"About CSA",news:"News & events",clips:"CSA Clips",faq:"Frequently asked questions",careers:"Careers",contact:"Contact us",profile:"My account"}
};

function Page({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){
  return <div className="mx-auto max-w-7xl px-4 py-8 md:px-8 md:py-12"><p className="text-xs font-black tracking-[.2em] text-[#ffc400]">{eyebrow}</p><h1 className="mt-2 font-display text-4xl uppercase sm:text-6xl">{title}</h1><div className="mt-8">{children}</div></div>;
}

export function PublicPage({view,lang,go,content}:{view:View;lang:Lang;go:(v:View)=>void;content:SiteContent}){
  const c=copy[lang];
  if(view==="member"||view==="profile") return <ProfilePage lang={lang} go={go}/>;
  if(view==="my-products") return <MyProducts lang={lang} go={go}/>;
  if(view==="branches") return <Branches lang={lang} content={content}/>;
  if(view==="advice") return <Editorial lang={lang} mode="advice" title={c.advice} content={content}/>;
  if(view==="about") return <About lang={lang} content={content}/>;
  if(view==="news") return <Editorial lang={lang} mode="news" title={c.news} content={content}/>;
  if(view==="clips") return <Clips lang={lang} content={content}/>;
  if(view==="faq") return <Faq lang={lang} content={content}/>;
  if(view==="careers") return <Careers lang={lang} content={content}/>;
  return <Contact lang={lang} content={content}/>;
}

function ProfilePage({lang,go}:{lang:Lang;go:(v:View)=>void}){
 const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/member/records",{cache:"no-store"}).then(async r=>{if(r.status===401)return {unauthorized:true};if(!r.ok)throw new Error();return r.json()}).then(setData).catch(()=>setData({error:true})).finally(()=>setLoading(false))},[]);
 if(loading)return <Page eyebrow="CSA MEMBER" title={copy[lang].profile}><p className="text-zinc-500">{lang==="th"?"กำลังโหลดข้อมูลสมาชิก...":"Loading member profile..."}</p></Page>;
 if(data?.unauthorized)return <Page eyebrow="CSA MEMBER" title={copy[lang].profile}><div className="border border-white/10 bg-[#111] p-8"><UserRound className="h-8 w-8 text-[#ffc400]"/><h2 className="mt-4 text-xl font-black">{lang==="th"?"กรุณาเข้าสู่ระบบด้วย LINE":"Sign in with LINE"}</h2><p className="mt-2 text-sm text-zinc-500">{lang==="th"?"เข้าสู่ระบบเพื่อดูบัญชีสมาชิก CSA ของคุณ":"Sign in to view your CSA member account."}</p></div></Page>;
 if(data?.error)return <Page eyebrow="CSA MEMBER" title={copy[lang].profile}><p className="text-red-400">{lang==="th"?"ไม่สามารถโหลดข้อมูลสมาชิกได้":"Could not load member profile."}</p></Page>;
 const m=data.member||{};const products=data.products||[];const claims=data.claims||[];const initials=String(m.display_name||"CSA").trim().slice(0,2).toUpperCase();
 return <Page eyebrow="CSA MEMBER" title={copy[lang].profile}><div className="border border-white/10 bg-[#111] p-5 md:p-7"><div className="flex flex-wrap items-center gap-4">{m.picture_url?<img src={m.picture_url} alt="" className="h-16 w-16 rounded-full object-cover"/>:<span className="grid h-16 w-16 place-items-center rounded-full bg-[#ffc400] text-xl font-black text-black">{initials}</span>}<div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black">{m.display_name||"CSA Member"}</h2><span className="rounded-full bg-emerald-500/15 px-2 py-1 text-[10px] font-black text-emerald-400">LINE CONNECTED</span></div><p className="mt-1 font-mono text-xs text-[#ffc400]">{m.id}</p><p className="mt-1 text-sm text-zinc-500">{lang==="th"?"บัญชีสมาชิก CSA ที่ยืนยันผ่าน LINE":"CSA member account verified with LINE"}</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><button onClick={()=>go("my-products")} className="border border-white/10 p-5 text-left hover:border-[#ffc400]"><PackageCheck className="h-5 w-5 text-[#ffc400]"/><p className="mt-3 text-2xl font-black">{products.length}</p><p className="text-sm text-zinc-500">{lang==="th"?"สินค้าที่ลงทะเบียน":"Registered products"}</p></button><button onClick={()=>go("claims")} className="border border-white/10 p-5 text-left hover:border-[#ffc400]"><ShieldCheck className="h-5 w-5 text-[#ffc400]"/><p className="mt-3 text-2xl font-black">{claims.length}</p><p className="text-sm text-zinc-500">{lang==="th"?"รายการเคลม":"Claims"}</p></button></div><div className="mt-6 border-t border-white/10 pt-5"><p className="text-xs leading-5 text-zinc-500">{lang==="th"?"ชื่อและรูปโปรไฟล์มาจากบัญชี LINE ที่ใช้เข้าสู่ระบบ ข้อมูลติดต่อ ที่อยู่ และคำสั่งซื้อจะแสดงเมื่อระบบรองรับการบันทึกข้อมูลจริงแล้ว":"Name and profile photo come from the LINE account used to sign in. Contact details, addresses and orders will appear only after those features have real stored data."}</p></div></div></Page>;
}
function MyProducts({lang,go}:{lang:Lang;go:(v:View)=>void}){
 const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/member/records",{cache:"no-store"}).then(async r=>{if(r.status===401)return {unauthorized:true};if(!r.ok)throw new Error();return r.json()}).then(setData).catch(()=>setData({error:true})).finally(()=>setLoading(false))},[]);
 if(loading)return <Page eyebrow="MY CSA" title={lang==="th"?"สินค้าของฉัน":"My products"}><p className="text-zinc-500">{lang==="th"?"กำลังโหลด...":"Loading..."}</p></Page>;
 if(data?.unauthorized)return <Page eyebrow="MY CSA" title={lang==="th"?"สินค้าของฉัน":"My products"}><div className="border border-white/10 bg-[#111] p-8"><UserRound className="h-8 w-8 text-[#ffc400]"/><h2 className="mt-4 text-xl font-black">{lang==="th"?"กรุณาเข้าสู่ระบบด้วย LINE":"Sign in with LINE"}</h2><p className="mt-2 text-sm text-zinc-500">{lang==="th"?"เข้าสู่ระบบก่อนดูสินค้าที่ลงทะเบียนและประวัติการเคลม":"Sign in to see your registered products and claim history."}</p><Button onClick={()=>go("member")} className="mt-5 bg-[#ffc400] text-black">{lang==="th"?"ไปที่สมาชิก":"Member login"}</Button></div></Page>;
 const products=data?.products||[],claims=data?.claims||[];
 return <Page eyebrow="MY CSA" title={lang==="th"?"สินค้าของฉัน":"My products"}><div className="grid gap-4 lg:grid-cols-2">{products.map((p:any)=>{const open=claims.filter((x:any)=>x.serial===p.serial&&!["completed","rejected"].includes(x.status)).length;return <article key={p.id} className="border border-[#ffc400]/30 bg-[#111] p-5"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center bg-[#ffc400] text-black"><ShockAbsorberIcon/></span><span className="bg-emerald-500/15 px-2 py-1 text-xs font-bold text-emerald-400">{p.status==="active"?(lang==="th"?"รับประกันอยู่":"WARRANTY ACTIVE"):p.status.toUpperCase()}</span></div><p className="mt-5 font-mono text-xs text-[#ffc400]">{p.serial}</p><h2 className="mt-1 text-xl font-black">CSA Suspension</h2><p className="mt-1 text-sm text-zinc-500">{lang==="th"?"ลงทะเบียน":"Registered"} · {String(p.created_at).slice(0,10)}</p><div className="mt-6 grid grid-cols-2 border-t border-white/10 pt-4 text-sm"><div><p className="text-xs text-zinc-600">{lang==="th"?"รหัสรับประกัน":"WARRANTY ID"}</p><p className="mt-1 font-mono font-bold">{p.warranty_id}</p></div><div><p className="text-xs text-zinc-600">{lang==="th"?"การเคลมที่เปิด":"OPEN CLAIMS"}</p><p className="mt-1 font-bold">{open}</p></div></div><Button onClick={()=>go("claims")} variant="outline" className="mt-5 border-white/20 bg-transparent text-white">{lang==="th"?"แจ้ง/ติดตามเคลม":"Claim / track"}</Button></article>})}<button onClick={()=>go("warranty")} className="min-h-64 border border-dashed border-white/20 p-6 text-left hover:border-[#ffc400]"><ShieldCheck className="h-7 w-7 text-[#ffc400]"/><h3 className="mt-4 text-xl font-black">{lang==="th"?"ลงทะเบียนสินค้าเพิ่ม":"Register another product"}</h3><p className="mt-2 text-sm text-zinc-500">{lang==="th"?"สแกน QR หรือกรอก Serial Number เพื่อเริ่มรับประกัน":"Scan QR or enter the serial number to activate warranty."}</p></button></div>{claims.length>0&&<section className="mt-8 border border-white/10 bg-[#111] p-5"><h2 className="text-xl font-black">{lang==="th"?"ประวัติการเคลม":"Claim history"}</h2><div className="mt-4 space-y-3">{claims.map((x:any)=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-3"><div><p className="font-mono text-sm text-[#ffc400]">{x.id}</p><p className="text-sm text-zinc-400">{x.serial} · {x.issue}</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold uppercase">{x.status}</span></div>)}</div></section>}</Page>;
}
function Branches({lang,content}:{lang:Lang;content:SiteContent}){
 const [q,setQ]=useState(""),[location,setLocation]=useState<{lat:number;lng:number}|null>(null),[geoState,setGeoState]=useState<"idle"|"loading"|"denied">("idle");
 const distance=(lat:number,lng:number)=>{if(!location)return null;const R=6371,toRad=(n:number)=>n*Math.PI/180,dLat=toRad(lat-location.lat),dLng=toRad(lng-location.lng),a=Math.sin(dLat/2)**2+Math.cos(toRad(location.lat))*Math.cos(toRad(lat))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))};
 const locate=()=>{if(!navigator.geolocation){setGeoState("denied");return}setGeoState("loading");navigator.geolocation.getCurrentPosition(p=>{setLocation({lat:p.coords.latitude,lng:p.coords.longitude});setGeoState("idle")},()=>setGeoState("denied"),{enableHighAccuracy:true,timeout:10000,maximumAge:300000})};
 const all=content.dealers.filter(x=>x.status==="published").map(x=>({...x,displayName:x.name[lang],displayPlace:x.place[lang],distance:x.latitude!=null&&x.longitude!=null?distance(x.latitude,x.longitude):null})).filter(x=>`${x.displayName} ${x.displayPlace}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>location?(a.distance??Infinity)-(b.distance??Infinity):a.sortOrder-b.sortOrder);
 const mapSrc=location?`https://www.google.com/maps?q=${location.lat},${location.lng}&z=11&output=embed`:all[0]?.latitude!=null&&all[0]?.longitude!=null?`https://www.google.com/maps?q=${all[0].latitude},${all[0].longitude}&z=12&output=embed`:"";
 return <Page eyebrow="AUTHORIZED NETWORK" title={copy[lang].branches}><div className="mb-5 flex flex-wrap gap-3"><button onClick={locate} disabled={geoState==="loading"} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#ffc400] px-5 font-black text-black"><Navigation className="h-5 w-5"/>{geoState==="loading"?(lang==="th"?"กำลังค้นหาตำแหน่ง...":"Locating..."):(lang==="th"?"ค้นหาตัวแทนใกล้ฉัน":"Find dealers near me")}</button>{location&&<span className="self-center text-sm font-bold text-emerald-400">● {lang==="th"?"ใช้ตำแหน่งปัจจุบันแล้ว":"Using your location"}</span>}{geoState==="denied"&&<span className="self-center text-sm text-zinc-500">{lang==="th"?"ไม่สามารถใช้ตำแหน่งได้ — ค้นหาจังหวัดหรือชื่อตัวแทนด้านล่าง":"Location unavailable — search by province or dealer below"}</span>}</div><div className="grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><section><label className="flex h-12 items-center border border-white/15 bg-[#111] px-4"><Search className="mr-3 h-4 w-4 text-[#ffc400]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={lang==="th"?"ค้นหาจังหวัดหรือชื่อตัวแทน":"Search province or dealer"} className="w-full bg-transparent outline-none"/></label><div className="mt-3 space-y-3">{all.length?all.map((x,i)=><article key={x.id} className="border border-white/10 bg-[#111] p-4"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center bg-[#ffc400] text-sm font-black text-black">{i+1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-bold">{x.displayName}</h2>{x.distance!=null&&<span className="rounded-full bg-[#ffc400]/10 px-2 py-1 text-xs font-black text-[#ffc400]">{x.distance.toFixed(1)} km</span>}</div><p className="mt-1 text-sm text-zinc-500"><MapPin className="mr-1 inline h-3 w-3"/>{x.displayPlace}</p><div className="mt-3 flex flex-wrap gap-3">{x.phone&&<a href={`tel:${x.phone.replace(/[^+\\d]/g,"")}`} className="text-sm font-bold text-[#ffc400]"><Phone className="mr-1 inline h-4 w-4"/>{x.phone}</a>}{x.mapUrl&&<a href={x.mapUrl} target="_blank" rel="noreferrer" className="text-sm font-bold text-white"><Navigation className="mr-1 inline h-4 w-4"/>{lang==="th"?"นำทาง Google Maps":"Google Maps directions"}</a>}</div></div></div></article>):<Empty lang={lang}/>}</div></section><div className="min-h-[420px] overflow-hidden border border-white/10 bg-[#151515]">{mapSrc?<iframe title="CSA dealer map" src={mapSrc} className="h-[520px] w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/>:<div className="grid h-[420px] place-items-center p-8 text-center"><div><MapPin className="mx-auto h-10 w-10 text-[#ffc400]"/><p className="mt-4 font-bold">{lang==="th"?"เพิ่มพิกัดตัวแทนใน CSA Admin เพื่อแสดงแผนที่":"Add dealer coordinates in CSA Admin to show the map"}</p></div></div>}</div></div></Page>;
}
function Editorial({lang,mode,title,content}:{lang:Lang;mode:"advice"|"news";title:string;content:SiteContent}){
 const items=content.editorial.filter(x=>x.type===mode&&x.status==="published").sort((a,b)=>a.sortOrder-b.sortOrder); const Icon=mode==="advice"?FileText:Newspaper;
 return <Page eyebrow={mode==="advice"?"KNOWLEDGE CENTER":"CSA UPDATE"} title={title}>{items.length?<div className="grid gap-4 md:grid-cols-3">{items.map(x=><article key={x.id} className="group border border-white/10 bg-[#111] p-5">{x.image?<img src={x.image} alt="" className="h-36 w-full object-cover"/>:<div className="flex h-36 items-center justify-center bg-black"><Icon className="h-10 w-10 text-[#ffc400]"/></div>}<p className="mt-5 text-xs font-bold text-[#ffc400]">{x.category||mode.toUpperCase()} {x.publishedAt&&`· ${x.publishedAt}`}</p><h2 className="mt-2 text-xl font-black leading-snug">{x.title[lang]}</h2><p className="mt-3 text-sm leading-6 text-zinc-400">{x.excerpt[lang]}</p>{x.url&&<a href={x.url} className="mt-5 inline-block text-sm font-bold text-[#ffc400]">{lang==="th"?"อ่านต่อ":"Read more"} →</a>}</article>)}</div>:<Empty lang={lang}/>}</Page>
}
function About({lang,content}:{lang:Lang;content:SiteContent}){return <Page eyebrow="ABOUT CSA" title={copy[lang].about}><section className="border border-white/10 bg-[#111] p-6 md:p-9"><p className="text-2xl font-black leading-tight">{content.about.headline[lang]}</p><p className="mt-5 leading-7 text-zinc-400">{content.about.description[lang]}</p></section></Page>}
function Clips({lang,content}:{lang:Lang;content:SiteContent}){const items=content.editorial.filter(x=>x.type==="clip"&&x.status==="published").sort((a,b)=>a.sortOrder-b.sortOrder);return <Page eyebrow="WATCH & LEARN" title={copy[lang].clips}>{items.length?<div className="grid gap-4 md:grid-cols-3">{items.map(x=><article key={x.id} className="border border-white/10 bg-[#111]">{x.image?<img src={x.image} alt="" className="h-44 w-full object-cover"/>:<div className="grid h-44 place-items-center bg-black"><Play className="text-[#ffc400]"/></div>}<div className="p-5"><p className="text-xs font-bold text-[#ffc400]">{x.category||"CSA CLIPS"}</p><h2 className="mt-2 text-lg font-black">{x.title[lang]}</h2><p className="mt-2 text-sm text-zinc-500">{x.excerpt[lang]}</p>{x.url&&<a href={x.url} className="mt-4 inline-block text-sm font-bold text-[#ffc400]">{lang==="th"?"ดูคลิป":"Watch clip"} →</a>}</div></article>)}</div>:<Empty lang={lang}/>}</Page>}
function Faq({lang,content}:{lang:Lang;content:SiteContent}){const [open,setOpen]=useState(0);const items=content.faqs.filter(x=>x.status==="published").sort((a,b)=>a.sortOrder-b.sortOrder);return <Page eyebrow="SUPPORT" title={copy[lang].faq}>{items.length?<div className="mx-auto max-w-3xl space-y-3">{items.map((x,i)=><article key={x.id} className="border border-white/10 bg-[#111]"><button onClick={()=>setOpen(open===i?-1:i)} className="flex w-full items-center justify-between p-5 text-left font-bold"><span><CircleHelp className="mr-3 inline h-5 w-5 text-[#ffc400]"/>{x.question[lang]}</span><ChevronDown className={`h-4 w-4 transition ${open===i?"rotate-180":""}`}/></button>{open===i&&<p className="border-t border-white/10 px-5 py-4 leading-7 text-zinc-400">{x.answer[lang]}</p>}</article>)}</div>:<Empty lang={lang}/>}</Page>}
function Careers({lang,content}:{lang:Lang;content:SiteContent}){const items=content.careers.filter(x=>x.status==="published").sort((a,b)=>a.sortOrder-b.sortOrder);return <Page eyebrow="JOIN CSA" title={copy[lang].careers}>{items.length?<div className="grid gap-4 lg:grid-cols-2">{items.map(x=><article key={x.id} className="border border-white/10 bg-[#111] p-6"><Building2 className="h-6 w-6 text-[#ffc400]"/><h2 className="mt-5 text-xl font-black">{x.title[lang]}</h2><p className="mt-2 text-sm text-zinc-500">{x.location[lang]}</p><p className="mt-4 text-sm leading-6 text-zinc-400">{x.description[lang]}</p>{x.email&&<a href={`mailto:${x.email}`} className="mt-6 inline-block font-bold text-[#ffc400]">{lang==="th"?"สมัครงาน":"Apply"} →</a>}</article>)}</div>:<Empty lang={lang}/>}</Page>}
function Contact({lang,content}:{lang:Lang;content:SiteContent}){const [sent,setSent]=useState(false);return <Page eyebrow="CONTACT CSA" title={copy[lang].contact}><div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><aside className="space-y-3">{[[Phone,content.contact.phone],[Mail,content.contact.email],[MapPin,content.contact.address[lang]]].map(([I,t])=>{const Icon=I as typeof Phone;return <div key={t as string} className="flex items-center gap-4 border border-white/10 bg-[#111] p-5"><Icon className="h-5 w-5 text-[#ffc400]"/><span className="font-bold">{t as string}</span></div>})}</aside><section className="border border-white/10 bg-[#111] p-5 md:p-7">{sent?<div className="py-12 text-center"><PackageCheck className="mx-auto h-12 w-12 text-[#ffc400]"/><h2 className="mt-4 text-2xl font-black">{lang==="th"?"ส่งข้อความแล้ว":"Message sent"}</h2></div>:<div className="grid gap-4 sm:grid-cols-2"><Field label={lang==="th"?"ชื่อ":"Name"}/><Field label={lang==="th"?"เบอร์โทร":"Phone"}/><div className="sm:col-span-2"><Label>{lang==="th"?"ข้อความ":"Message"}</Label><Textarea className="mt-2 min-h-32 border-white/15 bg-black/40"/></div><Button onClick={()=>setSent(true)} className="bg-[#ffc400] text-black sm:col-span-2"><Send className="h-4 w-4"/>{lang==="th"?"ส่งข้อความ":"Send message"}</Button></div>}</section></div></Page>}
function Empty({lang}:{lang:Lang}){return <div className="rounded-2xl border border-white/10 bg-[#111] p-10 text-center text-zinc-500">{lang==="th"?"ยังไม่มีเนื้อหาที่เผยแพร่":"No published content yet"}</div>}

function Field({label,value}:{label:string;value?:string}){return <div><Label>{label}</Label><Input defaultValue={value} className="mt-2 border-white/15 bg-black/40"/></div>}
function Address({title,text,primary}:{title:string;text:string;primary?:boolean}){return <article className="border border-white/10 p-4"><div className="flex justify-between"><b>{title}</b>{primary&&<span className="text-xs font-bold text-[#ffc400]">PRIMARY</span>}</div><p className="mt-3 text-sm leading-6 text-zinc-500">{text}</p></article>}
function Favorite({name,model}:{name:string;model:string}){return <article className="border border-white/10 p-4"><Heart className="h-5 w-5 fill-[#ffc400] text-[#ffc400]"/><h3 className="mt-4 font-bold">{name}</h3><p className="mt-1 text-xs text-zinc-500">{model}</p></article>}
