import { Mail, Phone } from "lucide-react";
import type { Lang, View } from "@/src/types/portal";

function FooterLinks({ title, items, onNavigate }: { title: string; items: {label:string;view:View}[]; onNavigate?:(view:View)=>void }) {
  return <div><h3 className="text-xl font-black">{title}</h3><ul className="mt-5 space-y-4 text-zinc-400">{items.map((item) => <li key={item.label}><button onClick={()=>onNavigate?.(item.view)} className="hover:text-white">{item.label}</button></li>)}</ul></div>;
}

export function SiteFooter({ lang, onNavigate }: { lang: Lang; onNavigate?:(view:View)=>void }) {
  return <footer className="bg-black px-6 py-14 text-white sm:px-10"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black">{lang === "th" ? "ติดต่อ" : "Contact"}</h2><div className="mt-7 grid gap-5 sm:grid-cols-2"><a href="tel:020000000" className="flex items-center gap-4 text-xl font-black text-[#ffc400]"><Phone className="h-8 w-8 text-white"/>Call 02-000-0000</a><a href="mailto:service@csa.co.th" className="flex items-center gap-4 text-lg font-bold"><Mail className="h-7 w-7"/>service@csa.co.th</a></div>
    <div className="mt-12 grid gap-10 border-b border-white/20 pb-12 md:grid-cols-[1fr_1fr_1fr]"><div><img src="/csa-logo.svg" alt="CSA High Performance Suspension" className="h-20 w-auto brightness-0 invert"/><p className="mt-4 max-w-sm leading-7 text-zinc-400">{lang === "th" ? "ผู้เชี่ยวชาญช่วงล่างสมรรถนะสูงสำหรับรถตู้ พร้อมบริการ รับประกัน และดูแลหลังการขาย" : "High-performance van suspension with warranty and after-sales support."}</p><div className="mt-6 flex gap-3"><a className="social-dot" href="https://facebook.com" target="_blank" rel="noreferrer" aria-label="Facebook">f</a><a className="social-dot text-xs" href="https://instagram.com" target="_blank" rel="noreferrer" aria-label="Instagram">IG</a><a className="social-dot text-xs" href="https://line.me" target="_blank" rel="noreferrer" aria-label="LINE">LINE</a></div></div><FooterLinks onNavigate={onNavigate} title={lang === "th" ? "สินค้าและบริการ" : "Products"} items={[{label:"โช้คอัพ CSA",view:"shop"},{label:"ค้นหาตามรุ่นรถ",view:"shop"},{label:"ลงทะเบียนรับประกัน",view:"warranty"},{label:"แจ้งเคลม",view:"claims"}]}/><FooterLinks onNavigate={onNavigate} title={lang === "th" ? "ดูแลลูกค้า" : "Support"} items={[{label:"บัญชีของฉัน",view:"profile"},{label:"ติดตามคำสั่งซื้อ",view:"profile"},{label:"คำถามที่พบบ่อย",view:"faq"},{label:"ติดต่อเรา",view:"contact"}]}/></div>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-5 text-sm text-zinc-500"><p>© 2026 CSA. All rights reserved.</p><div className="flex gap-2">{["VISA", "Mastercard", "JCB", "UnionPay"].map((item) => <span key={item} className="rounded bg-white px-2 py-1 text-xs font-black text-black">{item}</span>)}</div></div></div></footer>;
}
