"use client";

import { useEffect, useState } from "react";
import { Globe2, ImagePlus, Loader2, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { defaultSiteContent,type SiteContent } from "@/src/data/siteContent";

export function WebsiteAdmin(){
  const [value,setValue]=useState<SiteContent>(defaultSiteContent);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState<"hero"|"promotion"|null>(null);const [message,setMessage]=useState("");
  useEffect(()=>{fetch("/csa-admin/api/site-content",{cache:"no-store"}).then(r=>r.json()).then(d=>setValue(d.content||defaultSiteContent)).finally(()=>setLoading(false))},[]);
  const save=async()=>{setSaving(true);setMessage("");try{const r=await fetch("/csa-admin/api/site-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage("บันทึกและอัปเดต Customer UI เรียบร้อย")}catch(e){setMessage(e instanceof Error?e.message:"บันทึกไม่สำเร็จ")}finally{setSaving(false)}};
  const upload=async(file:File|undefined,target:"hero"|"promotion")=>{if(!file)return;if(file.size>8*1024*1024){setMessage("ไฟล์ใหญ่เกิน 8 MB");return}setUploading(target);setMessage("กำลังอัปโหลดรูป…");try{const form=new FormData();form.append("file",file);const r=await fetch("/csa-admin/api/upload",{method:"POST",body:form});const d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||"อัปโหลดไม่สำเร็จ");const next=target==="hero"?{...value,hero:{...value.hero,image:String(d.url)}}:{...value,promotion:{...value.promotion,image:String(d.url)}};setValue(next);const saveResponse=await fetch("/csa-admin/api/site-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});const saved=await saveResponse.json();if(!saveResponse.ok)throw new Error(saved.error||"บันทึกรูปไม่สำเร็จ");setMessage(target==="hero"?"อัปโหลดและบันทึกรูป Hero เรียบร้อย":"อัปโหลดและบันทึกรูปโปรโมชั่นเรียบร้อย") }catch(e){setMessage(e instanceof Error?e.message:"อัปโหลดไม่สำเร็จ")}finally{setUploading(null)}};
  if(loading)return <div className="grid h-64 place-items-center"><Loader2 className="animate-spin text-[#ffc400]"/></div>;
  return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold tracking-[.18em] text-[#ffc400]">WEBSITE CONTENT</p><h2 className="mt-1 text-3xl font-black">หน้าเว็บไซต์</h2><p className="mt-2 text-sm text-zinc-500">แก้ข้อความ รูป โปรโมชัน ลิงก์ และข้อมูลติดต่อ โดยไม่ต้องแก้โค้ด</p></div><Button onClick={()=>void save()} disabled={saving} className="bg-[#ffc400] text-black hover:bg-[#ffd43b]">{saving?<Loader2 className="animate-spin"/>:<Save/>}บันทึก</Button></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><Panel title="Hero หน้าแรก"><Upload image={value.hero.image} busy={uploading==="hero"} onFile={f=>void upload(f,"hero")}/><Text label="รูปภาพ URL" value={value.hero.image} set={image=>setValue({...value,hero:{...value.hero,image}})}/><Pair label="ป้ายด้านบน" th={value.hero.badge.th} en={value.hero.badge.en} set={(th,en)=>setValue({...value,hero:{...value.hero,badge:{th,en}}})}/><Pair label="หัวข้อหลัก" th={value.hero.title.th} en={value.hero.title.en} set={(th,en)=>setValue({...value,hero:{...value.hero,title:{th,en}}})}/><Pair label="ข้อความสีเหลือง" th={value.hero.highlight.th} en={value.hero.highlight.en} set={(th,en)=>setValue({...value,hero:{...value.hero,highlight:{th,en}}})}/><Pair label="คำอธิบาย" area th={value.hero.description.th} en={value.hero.description.en} set={(th,en)=>setValue({...value,hero:{...value.hero,description:{th,en}}})}/><Pair label="ข้อความบนปุ่ม" th={value.hero.button.th} en={value.hero.button.en} set={(th,en)=>setValue({...value,hero:{...value.hero,button:{th,en}}})}/></Panel>
      <Panel title="โปรโมชั่น"><div className="flex items-center justify-between rounded-xl border border-white/10 p-3"><span className="font-bold">แสดงโปรโมชั่น</span><Switch checked={value.promotion.active} onCheckedChange={active=>setValue({...value,promotion:{...value.promotion,active}})}/></div><Upload image={value.promotion.image} busy={uploading==="promotion"} onFile={f=>void upload(f,"promotion")}/><Text label="รูปโปรโมชั่น URL" value={value.promotion.image} set={image=>setValue({...value,promotion:{...value.promotion,image}})}/><Pair label="หัวข้อ" th={value.promotion.title.th} en={value.promotion.title.en} set={(th,en)=>setValue({...value,promotion:{...value.promotion,title:{th,en}}})}/><Pair label="รายละเอียด" area th={value.promotion.description.th} en={value.promotion.description.en} set={(th,en)=>setValue({...value,promotion:{...value.promotion,description:{th,en}}})}/><Pair label="ข้อความบนปุ่ม" th={value.promotion.button.th} en={value.promotion.button.en} set={(th,en)=>setValue({...value,promotion:{...value.promotion,button:{th,en}}})}/><Text label="ลิงก์ปลายทาง" value={value.promotion.url} set={url=>setValue({...value,promotion:{...value.promotion,url}})}/><div className="grid grid-cols-2 gap-3"><Text label="วันเริ่ม" type="date" value={value.promotion.startsAt} set={startsAt=>setValue({...value,promotion:{...value.promotion,startsAt}})}/><Text label="วันสิ้นสุด" type="date" value={value.promotion.endsAt} set={endsAt=>setValue({...value,promotion:{...value.promotion,endsAt}})}/></div></Panel>
      <Panel title="ข้อมูลติดต่อและลิงก์"><Text label="โทรศัพท์" value={value.contact.phone} set={phone=>setValue({...value,contact:{...value.contact,phone}})}/><Text label="อีเมล" value={value.contact.email} set={email=>setValue({...value,contact:{...value.contact,email}})}/><Text label="Facebook" value={value.contact.facebook} set={facebook=>setValue({...value,contact:{...value.contact,facebook}})}/><Text label="Instagram" value={value.contact.instagram} set={instagram=>setValue({...value,contact:{...value.contact,instagram}})}/><Text label="LINE" value={value.contact.line} set={line=>setValue({...value,contact:{...value.contact,line}})}/><Pair label="ปุ่มค้นหาตัวแทน" th={value.dealerButton.th} en={value.dealerButton.en} set={(th,en)=>setValue({...value,dealerButton:{th,en}})}/></Panel></div>{message&&<p className={`mt-4 rounded-xl border px-4 py-3 text-sm font-bold ${message.includes("เรียบร้อย")?"border-emerald-500/20 bg-emerald-500/10 text-emerald-400":message.includes("กำลัง")?"border-[#ffc400]/20 bg-[#ffc400]/10 text-[#ffc400]":"border-red-500/20 bg-red-500/10 text-red-400"}`}>{message.includes("เรียบร้อย")?"● บันทึกแล้ว · ":message.includes("กำลัง")?"● กำลังดำเนินการ · ":"● เกิดข้อผิดพลาด · "}{message}</p>}</div>;
}

function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border border-white/10 bg-[#111] p-5"><h3 className="flex items-center gap-2 text-xl font-black"><Globe2 className="text-[#ffc400]"/>{title}</h3>{children}</section>}
function Text({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <div><Label>{label}</Label><Input type={type} value={value} onChange={e=>set(e.target.value)} className="mt-2 border-white/15 bg-black/40"/></div>}
function Pair({label,th,en,set,area}:{label:string;th:string;en:string;set:(th:string,en:string)=>void;area?:boolean}){const C=area?Textarea:Input;return <div><Label>{label}</Label><div className="mt-2 grid gap-2 sm:grid-cols-2"><C value={th} onChange={e=>set(e.target.value,en)} placeholder="ภาษาไทย" className="border-white/15 bg-black/40"/><C value={en} onChange={e=>set(th,e.target.value)} placeholder="English" className="border-white/15 bg-black/40"/></div></div>}
function Upload({image,onFile,busy}:{image:string;onFile:(f:File|undefined)=>void;busy:boolean}){return <div className="flex flex-wrap items-center gap-3">{image?<img src={image} alt="ตัวอย่างรูปที่อัปโหลด" className="h-24 w-36 rounded-xl bg-white object-cover"/>:<div className="grid h-24 w-36 place-items-center rounded-xl bg-black"><ImagePlus/></div>}<div><label className={`inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#ffc400] px-4 py-2 text-sm font-black text-black ${busy?"pointer-events-none opacity-60":"cursor-pointer"}`}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<ImagePlus className="h-4 w-4"/>}{busy?"กำลังอัปโหลด…":"เลือกรูปจากเครื่อง"}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" className="hidden" disabled={busy} onChange={e=>{onFile(e.target.files?.[0]);e.currentTarget.value=""}}/></label><p className="mt-2 text-xs text-zinc-500">PNG, JPG, WEBP หรือ SVG · ไม่เกิน 8 MB · บันทึกอัตโนมัติ</p></div></div>}
