"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, CircleAlert, Globe2, ImagePlus, Loader2, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { defaultSiteContent,normalizeSiteContent,type SiteContent } from "@/src/data/siteContent";

type Target="hero"|"promotion";
type UploadState={target:Target|null;stage:"idle"|"uploading"|"saving"|"verifying"|"success"|"error";message:string};
const idle:UploadState={target:null,stage:"idle",message:""};

export function WebsiteAdmin(){
  const [value,setValue]=useState<SiteContent>(defaultSiteContent);
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
  const [upload,setUpload]=useState<UploadState>(idle);const [message,setMessage]=useState("");
  useEffect(()=>{fetch("/csa-admin/api/site-content",{cache:"no-store"}).then(r=>r.json()).then(d=>setValue(normalizeSiteContent(d.content))).finally(()=>setLoading(false))},[]);
  const persist=async(next:SiteContent)=>{const r=await fetch("/csa-admin/api/site-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});const d=await r.json();if(!r.ok)throw new Error(d.error||"บันทึกไม่สำเร็จ")};
  const save=async()=>{setSaving(true);setMessage("");try{await persist(value);setMessage("บันทึกและอัปเดต Customer UI เรียบร้อย")}catch(e){setMessage(e instanceof Error?e.message:"บันทึกไม่สำเร็จ")}finally{setSaving(false)}};
  const uploadImage=async(file:File|undefined,target:Target)=>{
    if(!file)return;const allowed=["image/png","image/jpeg","image/webp","image/svg+xml"];
    if(!allowed.includes(file.type)){setUpload({target,stage:"error",message:"รองรับเฉพาะ PNG, JPG, WEBP หรือ SVG"});return}
    if(file.size>8*1024*1024){setUpload({target,stage:"error",message:"ไฟล์ใหญ่เกิน 8 MB"});return}
    try{
      setUpload({target,stage:"uploading",message:"กำลังอัปโหลดรูป…"});
      const form=new FormData();form.append("file",file);const r=await fetch("/csa-admin/api/upload",{method:"POST",body:form});const d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||"อัปโหลดไม่สำเร็จ");
      const next=target==="hero"?{...value,hero:{...value.hero,image:String(d.url)}}:{...value,promotion:{...value.promotion,image:String(d.url)}};
      setUpload({target,stage:"saving",message:"กำลังบันทึกอัตโนมัติ…"});await persist(next);setValue(next);
      setUpload({target,stage:"verifying",message:"กำลังตรวจสอบรูปบนเว็บไซต์…"});const verify=await fetch(String(d.url),{cache:"no-store"});if(!verify.ok)throw new Error("บันทึกแล้ว แต่ยังเปิดรูปไม่ได้ กรุณาลองอีกครั้ง");
      setUpload({target,stage:"success",message:"อัปโหลด บันทึก และตรวจสอบรูปสำเร็จ"});
    }catch(e){setUpload({target,stage:"error",message:e instanceof Error?e.message:"อัปโหลดไม่สำเร็จ"})}
  };
  if(loading)return <div className="grid h-64 place-items-center"><Loader2 className="animate-spin text-[#ffc400]"/></div>;
  return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold tracking-[.18em] text-[#ffc400]">WEBSITE CONTENT</p><h2 className="mt-1 text-3xl font-black">หน้าเว็บไซต์</h2><p className="mt-2 text-sm text-zinc-500">แก้ข้อความ รูป โปรโมชัน ลิงก์ และข้อมูลติดต่อ โดยไม่ต้องแก้โค้ด</p></div><Button onClick={()=>void save()} disabled={saving} className="rounded-xl bg-[#ffc400] text-black hover:bg-[#ffd43b]">{saving?<Loader2 className="animate-spin"/>:<Save/>}บันทึก</Button></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><Panel title="Hero หน้าแรก"><Upload image={value.hero.image} state={upload.target==="hero"?upload:idle} onFile={f=>void uploadImage(f,"hero")}/><Text label="รูปภาพ URL" value={value.hero.image} set={image=>setValue({...value,hero:{...value.hero,image}})}/><Pair label="ป้ายด้านบน" th={value.hero.badge.th} en={value.hero.badge.en} set={(th,en)=>setValue({...value,hero:{...value.hero,badge:{th,en}}})}/><Pair label="หัวข้อหลัก" th={value.hero.title.th} en={value.hero.title.en} set={(th,en)=>setValue({...value,hero:{...value.hero,title:{th,en}}})}/><Pair label="ข้อความสีเหลือง" th={value.hero.highlight.th} en={value.hero.highlight.en} set={(th,en)=>setValue({...value,hero:{...value.hero,highlight:{th,en}}})}/><Pair label="คำอธิบาย" area th={value.hero.description.th} en={value.hero.description.en} set={(th,en)=>setValue({...value,hero:{...value.hero,description:{th,en}}})}/><Pair label="ข้อความบนปุ่ม" th={value.hero.button.th} en={value.hero.button.en} set={(th,en)=>setValue({...value,hero:{...value.hero,button:{th,en}}})}/></Panel>
      <Panel title="โปรโมชั่น"><div className="flex items-center justify-between rounded-xl border border-white/10 p-3"><span className="font-bold">แสดงโปรโมชั่น</span><Switch checked={value.promotion.active} onCheckedChange={active=>setValue({...value,promotion:{...value.promotion,active}})}/></div><Upload image={value.promotion.image} state={upload.target==="promotion"?upload:idle} onFile={f=>void uploadImage(f,"promotion")}/><Text label="รูปโปรโมชั่น URL" value={value.promotion.image} set={image=>setValue({...value,promotion:{...value.promotion,image}})}/><Pair label="หัวข้อ" th={value.promotion.title.th} en={value.promotion.title.en} set={(th,en)=>setValue({...value,promotion:{...value.promotion,title:{th,en}}})}/><Pair label="รายละเอียด" area th={value.promotion.description.th} en={value.promotion.description.en} set={(th,en)=>setValue({...value,promotion:{...value.promotion,description:{th,en}}})}/><Pair label="ข้อความบนปุ่ม" th={value.promotion.button.th} en={value.promotion.button.en} set={(th,en)=>setValue({...value,promotion:{...value.promotion,button:{th,en}}})}/><Text label="ลิงก์ปลายทาง" value={value.promotion.url} set={url=>setValue({...value,promotion:{...value.promotion,url}})}/><div className="grid grid-cols-2 gap-3"><Text label="วันเริ่ม" type="date" value={value.promotion.startsAt} set={startsAt=>setValue({...value,promotion:{...value.promotion,startsAt}})}/><Text label="วันสิ้นสุด" type="date" value={value.promotion.endsAt} set={endsAt=>setValue({...value,promotion:{...value.promotion,endsAt}})}/></div></Panel>
      <Panel title="ข้อมูลติดต่อและลิงก์"><Text label="โทรศัพท์" value={value.contact.phone} set={phone=>setValue({...value,contact:{...value.contact,phone}})}/><Text label="อีเมล" value={value.contact.email} set={email=>setValue({...value,contact:{...value.contact,email}})}/><Text label="Facebook" value={value.contact.facebook} set={facebook=>setValue({...value,contact:{...value.contact,facebook}})}/><Text label="Instagram" value={value.contact.instagram} set={instagram=>setValue({...value,contact:{...value.contact,instagram}})}/><Text label="LINE" value={value.contact.line} set={line=>setValue({...value,contact:{...value.contact,line}})}/><Pair label="ปุ่มค้นหาตัวแทน" th={value.dealerButton.th} en={value.dealerButton.en} set={(th,en)=>setValue({...value,dealerButton:{th,en}})}/></Panel></div>{message&&<p className="mt-4 font-bold text-emerald-400">{message}</p>}</div>;
}

function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border border-white/10 bg-[#111] p-5"><h3 className="flex items-center gap-2 text-xl font-black"><Globe2 className="text-[#ffc400]"/>{title}</h3>{children}</section>}
function Text({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <div><Label>{label}</Label><Input type={type} value={value} onChange={e=>set(e.target.value)} className="mt-2 border-white/15 bg-black/40"/></div>}
function Pair({label,th,en,set,area}:{label:string;th:string;en:string;set:(th:string,en:string)=>void;area?:boolean}){const C=area?Textarea:Input;return <div><Label>{label}</Label><div className="mt-2 grid gap-2 sm:grid-cols-2"><C value={th} onChange={e=>set(e.target.value,en)} placeholder="ภาษาไทย" className="border-white/15 bg-black/40"/><C value={en} onChange={e=>set(th,e.target.value)} placeholder="English" className="border-white/15 bg-black/40"/></div></div>}
function Upload({image,onFile,state}:{image:string;onFile:(f:File|undefined)=>void;state:UploadState}){const busy=["uploading","saving","verifying"].includes(state.stage);return <div className="flex flex-wrap items-center gap-3">{image?<img src={image} alt="ตัวอย่างรูปที่อัปโหลด" className="h-24 w-36 rounded-xl bg-white object-cover"/>:<div className="grid h-24 w-36 place-items-center rounded-xl bg-black"><ImagePlus/></div>}<div><label className={`inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#ffc400] px-4 py-2 text-sm font-black text-black transition hover:bg-[#ffd43b] ${busy?"pointer-events-none opacity-60":"cursor-pointer"}`}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<ImagePlus className="h-4 w-4"/>}{busy?state.message:"เลือกรูปจากเครื่อง"}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" className="hidden" disabled={busy} onChange={e=>{onFile(e.target.files?.[0]);e.currentTarget.value=""}}/></label><p className="mt-2 text-xs text-zinc-500">PNG, JPG, WEBP หรือ SVG · ไม่เกิน 8 MB · บันทึกอัตโนมัติ</p>{state.stage!=="idle"&&<p className={`mt-2 flex items-center gap-1.5 text-xs font-bold ${state.stage==="success"?"text-emerald-400":state.stage==="error"?"text-red-400":"text-[#ffc400]"}`}>{state.stage==="success"?<CheckCircle2 className="h-4 w-4"/>:state.stage==="error"?<CircleAlert className="h-4 w-4"/>:<Loader2 className="h-4 w-4 animate-spin"/>}{state.message}</p>}</div></div>}
