"use client";

import { useEffect, useState } from "react";
import { Globe2, ImagePlus, Loader2, Plus, Save, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { defaultSiteContent,normalizeSiteContent,type CareerItem,type DealerItem,type EditorialItem,type FaqItem,type SiteContent } from "@/src/data/siteContent";

type Notice={kind:"loading"|"success"|"error";text:string}|null;
const uid=(prefix:string)=>prefix+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7);
const emptyEditorial=(type:EditorialItem["type"]):EditorialItem=>({id:uid(type),type,title:{th:"",en:""},excerpt:{th:"",en:""},body:{th:"",en:""},image:"",url:"",category:"",publishedAt:"",status:"draft",sortOrder:0});
const emptyFaq=():FaqItem=>({id:uid("faq"),question:{th:"",en:""},answer:{th:"",en:""},status:"draft",sortOrder:0});
const emptyDealer=():DealerItem=>({id:uid("dealer"),name:{th:"",en:""},place:{th:"",en:""},phone:"",mapUrl:"",latitude:null,longitude:null,status:"draft",sortOrder:0});
const emptyCareer=():CareerItem=>({id:uid("career"),title:{th:"",en:""},location:{th:"",en:""},description:{th:"",en:""},email:"",status:"draft",sortOrder:0});

export function WebsiteAdmin(){
 const [value,setValue]=useState<SiteContent>(defaultSiteContent),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState<"hero"|"promotion"|null>(null),[notice,setNotice]=useState<Notice>(null);
 useEffect(()=>{fetch("/csa-admin/api/site-content",{cache:"no-store"}).then(r=>r.json()).then(d=>setValue(normalizeSiteContent(d.content))).catch(()=>setNotice({kind:"error",text:"โหลดข้อมูลเว็บไซต์ไม่สำเร็จ"})).finally(()=>setLoading(false))},[]);
 const persist=async(next=value)=>{const r=await fetch("/csa-admin/api/site-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});const d=await r.json();if(!r.ok)throw new Error(d.error||"บันทึกไม่สำเร็จ")};
 const save=async()=>{setSaving(true);setNotice({kind:"loading",text:"กำลังบันทึก…"});try{await persist();setNotice({kind:"success",text:"บันทึกและอัปเดต Customer UI เรียบร้อย"})}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"บันทึกไม่สำเร็จ"})}finally{setSaving(false)}};
 const upload=async(file:File|undefined,target:"hero"|"promotion")=>{if(!file)return;const allowed=["image/png","image/jpeg","image/webp","image/svg+xml"];if(!allowed.includes(file.type)){setNotice({kind:"error",text:"รองรับเฉพาะ PNG, JPG, WEBP หรือ SVG"});return}if(file.size>8*1024*1024){setNotice({kind:"error",text:"ไฟล์ใหญ่เกิน 8 MB"});return}setUploading(target);setNotice({kind:"loading",text:"กำลังอัปโหลดรูป…"});try{const form=new FormData();form.append("file",file);const r=await fetch("/csa-admin/api/upload",{method:"POST",body:form});const d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||"อัปโหลดไม่สำเร็จ");const next=target==="hero"?{...value,hero:{...value.hero,image:String(d.url)}}:{...value,promotion:{...value.promotion,image:String(d.url)}};setValue(next);await persist(next);setNotice({kind:"success",text:target==="hero"?"อัปโหลดและบันทึกรูป Hero เรียบร้อย":"อัปโหลดและบันทึกรูปโปรโมชั่นเรียบร้อย"})}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"อัปโหลดไม่สำเร็จ"})}finally{setUploading(null)}};
 const updateEditorial=(id:string,patch:Partial<EditorialItem>)=>setValue(v=>({...v,editorial:v.editorial.map(x=>x.id===id?{...x,...patch}:x)}));
 if(loading)return <div className="grid h-64 place-items-center"><Loader2 className="animate-spin text-[#ffc400]"/></div>;
 return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold tracking-[.18em] text-[#ffc400]">WEBSITE CONTENT</p><h2 className="mt-1 text-3xl font-black">หน้าเว็บไซต์</h2><p className="mt-2 text-sm text-zinc-500">จัดการ Hero, โปรโมชั่น และเนื้อหาที่ลูกค้าเห็นจากจุดเดียว</p></div><Button onClick={()=>void save()} disabled={saving} className="bg-[#ffc400] text-black hover:bg-[#ffd43b]">{saving?<Loader2 className="animate-spin"/>:<Save/>}บันทึกทั้งหมด</Button></div>
 <div className="mt-5 grid gap-5 xl:grid-cols-2">
  <Panel title="Hero หน้าแรก"><Upload image={value.hero.image} busy={uploading==="hero"} onFile={f=>void upload(f,"hero")}/><Text label="รูปภาพ URL" value={value.hero.image} set={image=>setValue({...value,hero:{...value.hero,image}})}/><Pair label="ป้ายด้านบน" th={value.hero.badge.th} en={value.hero.badge.en} set={(th,en)=>setValue({...value,hero:{...value.hero,badge:{th,en}}})}/><Pair label="หัวข้อหลัก" th={value.hero.title.th} en={value.hero.title.en} set={(th,en)=>setValue({...value,hero:{...value.hero,title:{th,en}}})}/><Pair label="ข้อความสีเหลือง" th={value.hero.highlight.th} en={value.hero.highlight.en} set={(th,en)=>setValue({...value,hero:{...value.hero,highlight:{th,en}}})}/><Pair label="คำอธิบาย" area th={value.hero.description.th} en={value.hero.description.en} set={(th,en)=>setValue({...value,hero:{...value.hero,description:{th,en}}})}/><Pair label="ข้อความบนปุ่ม" th={value.hero.button.th} en={value.hero.button.en} set={(th,en)=>setValue({...value,hero:{...value.hero,button:{th,en}}})}/></Panel>
  <Panel title="โปรโมชั่น"><div className="flex items-center justify-between rounded-xl border border-white/10 p-3"><span className="font-bold">แสดงโปรโมชั่น</span><Switch checked={value.promotion.active} onCheckedChange={active=>setValue({...value,promotion:{...value.promotion,active}})}/></div><Upload image={value.promotion.image} busy={uploading==="promotion"} onFile={f=>void upload(f,"promotion")}/><Pair label="หัวข้อ" th={value.promotion.title.th} en={value.promotion.title.en} set={(th,en)=>setValue({...value,promotion:{...value.promotion,title:{th,en}}})}/><Pair label="รายละเอียด" area th={value.promotion.description.th} en={value.promotion.description.en} set={(th,en)=>setValue({...value,promotion:{...value.promotion,description:{th,en}}})}/><Text label="ลิงก์ปลายทาง" value={value.promotion.url} set={url=>setValue({...value,promotion:{...value.promotion,url}})}/></Panel>
  <Panel title="เกี่ยวกับ CSA"><Pair label="Headline" th={value.about.headline.th} en={value.about.headline.en} set={(th,en)=>setValue({...value,about:{...value.about,headline:{th,en}}})}/><Pair label="รายละเอียด" area th={value.about.description.th} en={value.about.description.en} set={(th,en)=>setValue({...value,about:{...value.about,description:{th,en}}})}/></Panel>
  <Panel title="ข้อมูลติดต่อ"><Text label="โทรศัพท์" value={value.contact.phone} set={phone=>setValue({...value,contact:{...value.contact,phone}})}/><Text label="อีเมล" value={value.contact.email} set={email=>setValue({...value,contact:{...value.contact,email}})}/><Pair label="ที่อยู่" th={value.contact.address.th} en={value.contact.address.en} set={(th,en)=>setValue({...value,contact:{...value.contact,address:{th,en}}})}/><Text label="Facebook" value={value.contact.facebook} set={facebook=>setValue({...value,contact:{...value.contact,facebook}})}/><Text label="Instagram" value={value.contact.instagram} set={instagram=>setValue({...value,contact:{...value.contact,instagram}})}/><Text label="TikTok" value={value.contact.tiktok} set={tiktok=>setValue({...value,contact:{...value.contact,tiktok}})}/><Text label="LINE" value={value.contact.line} set={line=>setValue({...value,contact:{...value.contact,line}})}/></Panel>
 </div>
 <CmsSection title="บทความ · ข่าวสาร · คลิป" onAdd={()=>setValue(v=>({...v,editorial:[emptyEditorial("advice"),...v.editorial]}))}>{value.editorial.map(item=><article key={item.id} className="rounded-2xl border border-white/10 bg-[#111] p-4"><div className="grid gap-3 md:grid-cols-3"><Select label="ประเภท" value={item.type} set={type=>updateEditorial(item.id,{type:type as EditorialItem["type"]})} options={[["advice","บทความ"],["news","ข่าวสาร"],["clip","คลิป"]]}/><Select label="สถานะ" value={item.status} set={status=>updateEditorial(item.id,{status:status as "draft"|"published"})} options={[["draft","Draft"],["published","Published"]]}/><Text label="วันที่เผยแพร่" type="date" value={item.publishedAt} set={publishedAt=>updateEditorial(item.id,{publishedAt})}/></div><Pair label="หัวข้อ" th={item.title.th} en={item.title.en} set={(th,en)=>updateEditorial(item.id,{title:{th,en}})}/><Pair label="คำโปรย" area th={item.excerpt.th} en={item.excerpt.en} set={(th,en)=>updateEditorial(item.id,{excerpt:{th,en}})}/><Pair label="เนื้อหา" area th={item.body.th} en={item.body.en} set={(th,en)=>updateEditorial(item.id,{body:{th,en}})}/><div className="grid gap-3 md:grid-cols-2"><Text label="รูป Cover URL" value={item.image} set={image=>updateEditorial(item.id,{image})}/><Text label={item.type==="clip"?"Video URL":"CTA URL"} value={item.url} set={url=>updateEditorial(item.id,{url})}/></div><Danger onClick={()=>setValue(v=>({...v,editorial:v.editorial.filter(x=>x.id!==item.id)}))}/></article>)}</CmsSection>
 <CmsSection title="FAQ" onAdd={()=>setValue(v=>({...v,faqs:[emptyFaq(),...v.faqs]}))}>{value.faqs.map(item=><article key={item.id} className="rounded-2xl border border-white/10 bg-[#111] p-4"><Select label="สถานะ" value={item.status} set={status=>setValue(v=>({...v,faqs:v.faqs.map(x=>x.id===item.id?{...x,status:status as "draft"|"published"}:x)}))} options={[["draft","Draft"],["published","Published"]]}/><Pair label="คำถาม" th={item.question.th} en={item.question.en} set={(th,en)=>setValue(v=>({...v,faqs:v.faqs.map(x=>x.id===item.id?{...x,question:{th,en}}:x)}))}/><Pair label="คำตอบ" area th={item.answer.th} en={item.answer.en} set={(th,en)=>setValue(v=>({...v,faqs:v.faqs.map(x=>x.id===item.id?{...x,answer:{th,en}}:x)}))}/><Danger onClick={()=>setValue(v=>({...v,faqs:v.faqs.filter(x=>x.id!==item.id)}))}/></article>)}</CmsSection>
 <CmsSection title="ตัวแทนจำหน่าย" onAdd={()=>setValue(v=>({...v,dealers:[emptyDealer(),...v.dealers]}))}>{value.dealers.map(item=><article key={item.id} className="rounded-2xl border border-white/10 bg-[#111] p-4"><Select label="สถานะ" value={item.status} set={status=>setValue(v=>({...v,dealers:v.dealers.map(x=>x.id===item.id?{...x,status:status as "draft"|"published"}:x)}))} options={[["draft","Draft"],["published","Published"]]}/><Pair label="ชื่อตัวแทน" th={item.name.th} en={item.name.en} set={(th,en)=>setValue(v=>({...v,dealers:v.dealers.map(x=>x.id===item.id?{...x,name:{th,en}}:x)}))}/><Pair label="พื้นที่" th={item.place.th} en={item.place.en} set={(th,en)=>setValue(v=>({...v,dealers:v.dealers.map(x=>x.id===item.id?{...x,place:{th,en}}:x)}))}/><div className="grid gap-3 md:grid-cols-3"><Text label="โทรศัพท์" value={item.phone} set={phone=>setValue(v=>({...v,dealers:v.dealers.map(x=>x.id===item.id?{...x,phone}:x)}))}/><Text label="Latitude" value={item.latitude==null?"":String(item.latitude)} set={latitude=>setValue(v=>({...v,dealers:v.dealers.map(x=>x.id===item.id?{...x,latitude:latitude===""?null:Number(latitude)}:x)}))}/><Text label="Longitude" value={item.longitude==null?"":String(item.longitude)} set={longitude=>setValue(v=>({...v,dealers:v.dealers.map(x=>x.id===item.id?{...x,longitude:longitude===""?null:Number(longitude)}:x)}))}/></div><Text label="Google Maps URL" value={item.mapUrl} set={mapUrl=>setValue(v=>({...v,dealers:v.dealers.map(x=>x.id===item.id?{...x,mapUrl}:x)}))}/><p className="mt-2 text-xs text-zinc-500">ใช้ Latitude/Longitude เพื่อเรียงตัวแทนที่ใกล้ลูกค้า และ Google Maps URL สำหรับปุ่มนำทาง</p><Danger onClick={()=>setValue(v=>({...v,dealers:v.dealers.filter(x=>x.id!==item.id)}))}/></article>)}</CmsSection>
 <CmsSection title="ร่วมงานกับเรา" onAdd={()=>setValue(v=>({...v,careers:[emptyCareer(),...v.careers]}))}>{value.careers.map(item=><article key={item.id} className="rounded-2xl border border-white/10 bg-[#111] p-4"><Select label="สถานะ" value={item.status} set={status=>setValue(v=>({...v,careers:v.careers.map(x=>x.id===item.id?{...x,status:status as "draft"|"published"}:x)}))} options={[["draft","Draft"],["published","Published"]]}/><Pair label="ตำแหน่ง" th={item.title.th} en={item.title.en} set={(th,en)=>setValue(v=>({...v,careers:v.careers.map(x=>x.id===item.id?{...x,title:{th,en}}:x)}))}/><Pair label="สถานที่" th={item.location.th} en={item.location.en} set={(th,en)=>setValue(v=>({...v,careers:v.careers.map(x=>x.id===item.id?{...x,location:{th,en}}:x)}))}/><Pair label="รายละเอียด" area th={item.description.th} en={item.description.en} set={(th,en)=>setValue(v=>({...v,careers:v.careers.map(x=>x.id===item.id?{...x,description:{th,en}}:x)}))}/><Text label="อีเมลรับสมัคร" value={item.email} set={email=>setValue(v=>({...v,careers:v.careers.map(x=>x.id===item.id?{...x,email}:x)}))}/><Danger onClick={()=>setValue(v=>({...v,careers:v.careers.filter(x=>x.id!==item.id)}))}/></article>)}</CmsSection>
 {notice&&<p aria-live="polite" className={`mt-5 rounded-xl border px-4 py-3 text-sm font-bold ${notice.kind==="success"?"border-emerald-500/20 bg-emerald-500/10 text-emerald-400":notice.kind==="loading"?"border-[#ffc400]/20 bg-[#ffc400]/10 text-[#ffc400]":"border-red-500/20 bg-red-500/10 text-red-400"}`}>● {notice.text}</p>}</div>
}

function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border border-white/10 bg-[#111] p-5"><h3 className="flex items-center gap-2 text-xl font-black"><Globe2 className="text-[#ffc400]"/>{title}</h3>{children}</section>}
function CmsSection({title,onAdd,children}:{title:string;onAdd:()=>void;children:React.ReactNode}){return <section className="mt-5"><div className="mb-3 flex items-center justify-between"><h3 className="text-xl font-black">{title}</h3><Button onClick={onAdd} className="bg-[#ffc400] text-black"><Plus/>เพิ่ม</Button></div><div className="grid gap-4">{children}</div></section>}
function Text({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <div><Label>{label}</Label><Input type={type} value={value} onChange={e=>set(e.target.value)} className="mt-2 border-white/15 bg-black/40"/></div>}
function Pair({label,th,en,set,area}:{label:string;th:string;en:string;set:(th:string,en:string)=>void;area?:boolean}){const C=area?Textarea:Input;return <div className="mt-3"><Label>{label}</Label><div className="mt-2 grid gap-2 sm:grid-cols-2"><C value={th} onChange={e=>set(e.target.value,en)} placeholder="ภาษาไทย" className="border-white/15 bg-black/40"/><C value={en} onChange={e=>set(th,e.target.value)} placeholder="English" className="border-white/15 bg-black/40"/></div></div>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:[string,string][]}){return <div><Label>{label}</Label><select value={value} onChange={e=>set(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-white/15 bg-black/40 px-3 text-sm">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>}
function Danger({onClick}:{onClick:()=>void}){return <button onClick={onClick} className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-red-400"><Trash2 className="h-4 w-4"/>ลบรายการ</button>}
function Upload({image,onFile,busy}:{image:string;onFile:(f:File|undefined)=>void;busy:boolean}){return <div className="flex flex-wrap items-center gap-3">{image?<img src={image} alt="ตัวอย่างรูปที่อัปโหลด" className="h-24 w-36 rounded-xl bg-white object-cover"/>:<div className="grid h-24 w-36 place-items-center rounded-xl bg-black"><ImagePlus/></div>}<div><label className={`inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#ffc400] px-4 py-2 text-sm font-black text-black ${busy?"pointer-events-none opacity-60":"cursor-pointer"}`}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<ImagePlus className="h-4 w-4"/>}{busy?"กำลังอัปโหลด…":"เลือกรูปจากเครื่อง"}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" className="hidden" disabled={busy} onChange={e=>{onFile(e.target.files?.[0]);e.currentTarget.value=""}}/></label><p className="mt-2 text-xs text-zinc-500">PNG, JPG, WEBP หรือ SVG · ไม่เกิน 8 MB · บันทึกอัตโนมัติ</p></div></div>}