import { env } from "cloudflare:workers";
import { cookies } from "next/headers";
const COOKIE="csa_member_session";
function db(){if(!env.DB)throw new Error("Database unavailable");return env.DB}
export async function ensureMemberSchema(){await db().prepare(`CREATE TABLE IF NOT EXISTS members (id TEXT PRIMARY KEY,line_user_id TEXT UNIQUE NOT NULL,display_name TEXT NOT NULL DEFAULT '',picture_url TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await db().prepare(`CREATE TABLE IF NOT EXISTS member_sessions (token_hash TEXT PRIMARY KEY,member_id TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
async function hash(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
export async function createMemberSession(memberId:string){await ensureMemberSchema();const token=crypto.randomUUID()+crypto.randomUUID();const tokenHash=await hash(token);const expires=new Date(Date.now()+30*86400000);await db().prepare("INSERT INTO member_sessions (token_hash,member_id,expires_at) VALUES (?,?,?)").bind(tokenHash,memberId,expires.toISOString()).run();(await cookies()).set(COOKIE,token,{httpOnly:true,secure:true,sameSite:"lax",path:"/",expires});}
export async function getMember(){await ensureMemberSchema();const token=(await cookies()).get(COOKIE)?.value;if(!token)return null;const row=await db().prepare(`SELECT m.id,m.display_name,m.picture_url FROM member_sessions s JOIN members m ON m.id=s.member_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP LIMIT 1`).bind(await hash(token)).first<{id:string;display_name:string;picture_url:string}>();return row??null}
export async function clearMemberSession(){const store=await cookies();const token=store.get(COOKIE)?.value;if(token){await ensureMemberSchema();await db().prepare("DELETE FROM member_sessions WHERE token_hash=?").bind(await hash(token)).run()}store.delete(COOKIE)}
export async function upsertLineMember(lineUserId:string,name:string,picture:string){await ensureMemberSchema();let row=await db().prepare("SELECT id FROM members WHERE line_user_id=?").bind(lineUserId).first<{id:string}>();const id=row?.id??`MBR-${crypto.randomUUID().slice(0,8).toUpperCase()}`;await db().prepare(`INSERT INTO members (id,line_user_id,display_name,picture_url) VALUES (?,?,?,?) ON CONFLICT(line_user_id) DO UPDATE SET display_name=excluded.display_name,picture_url=excluded.picture_url,updated_at=CURRENT_TIMESTAMP`).bind(id,lineUserId,name,picture).run();return id}